[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pokemon_crystal"
dynamic = ["version"]
description = "Pokemon Crystal"
authors = [
    {name = "James"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"pokemon_crystal.WorldClass" = "pokemon_crystal.Register:WORLD_CLASS"
"pokemon_crystal.WebWorldClass" = "pokemon_crystal.Register:WEB_WORLD_CLASS"
"pokemon_crystal.Client" = "pokemon_crystal.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["pokemon_crystal*", "pokemon_crystal"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "pokemon_crystal.Constants.VERSION"}
