[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pokemon_rb"
dynamic = ["version"]
description = "Pokemon Red and Blue"
authors = [
    {name = "Alchav"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"pokemon_rb.WorldClass" = "pokemon_rb.Register:WORLD_CLASS"
"pokemon_rb.WebWorldClass" = "pokemon_rb.Register:WEB_WORLD_CLASS"
"pokemon_rb.Client" = "pokemon_rb.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["pokemon_rb*", "pokemon_rb"]
exclude = ["pokemon_rb/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
