[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "soe"
dynamic = ["version"]
description = "MultiWorld: Secret of Evermore"
authors = [
    {name = "black-silver"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "pyevermizer==0.50.1",
]

[project.entry-points."mwgg.plugins"]
"soe.WorldClass" = "soe.Register:WORLD_CLASS"
"soe.WebWorldClass" = "soe.Register:WEB_WORLD_CLASS"
"soe.Client" = "soe.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["soe*", "soe"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "soe.Constants.VERSION"}
