[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "subnautica"
dynamic = ["version"]
description = "Subnautica"
authors = [
    {name = "Berserker66"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"subnautica.WorldClass" = "subnautica.Register:WORLD_CLASS"
"subnautica.WebWorldClass" = "subnautica.Register:WEB_WORLD_CLASS"
"subnautica.Client" = "subnautica.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "subnautica.Register:VERSION"}
