[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "smz3"
dynamic = ["version"]
description = "SMZ3"
authors = [
    {name = "lordlou"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"smz3.WorldClass" = "smz3.Register:WORLD_CLASS"
"smz3.WebWorldClass" = "smz3.Register:WEB_WORLD_CLASS"
"smz3.Client" = "smz3.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
