[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "yoshisisland"
dynamic = ["version"]
description = "Yoshi's Island"
authors = [
    {name = "Pink Switch"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"yoshisisland.WorldClass" = "yoshisisland.Register:WORLD_CLASS"
"yoshisisland.WebWorldClass" = "yoshisisland.Register:WEB_WORLD_CLASS"
"yoshisisland.Client" = "yoshisisland.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["yoshisisland*", "yoshisisland"]
exclude = ["yoshisisland/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
