[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "yoshisisland"
dynamic = ["version"]
description = "Yoshi"
authors = [
    {name = "Pink Switch"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"yoshisisland.WorldClass" = "yoshisisland.Register:WORLD_CLASS"
"yoshisisland.WebWorldClass" = "yoshisisland.Register:WEB_WORLD_CLASS"
"yoshisisland.Client" = "yoshisisland.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "yoshisisland.Register:VERSION"}
