[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "landstalker"
dynamic = ["version"]
description = "Landstalker - The Treasures of King Nole"
authors = [
    {name = "Dinopony"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"landstalker.WorldClass" = "landstalker.Register:WORLD_CLASS"
"landstalker.WebWorldClass" = "landstalker.Register:WEB_WORLD_CLASS"
"landstalker.Client" = "landstalker.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
