[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "hades"
dynamic = ["version"]
description = "MultiWorld: Hades"
authors = [
    {name = "Naix"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"hades.WorldClass" = "hades.Register:WORLD_CLASS"
"hades.WebWorldClass" = "hades.Register:WEB_WORLD_CLASS"
"hades.Client" = "hades.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["hades*", "hades"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "hades.Constants.VERSION"}
