[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "factorio_saws"
dynamic = ["version"]
description = "Factorio Space Age Without Space"
authors = [
    {name = "Alchav & Berserker66"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "factorio-rcon-py>=2.1.2",
]

[project.entry-points."mwgg.plugins"]
"factorio_saws.WorldClass" = "factorio_saws.Register:WORLD_CLASS"
"factorio_saws.WebWorldClass" = "factorio_saws.Register:WEB_WORLD_CLASS"
"factorio_saws.Client" = "factorio_saws.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "factorio_saws.Register:VERSION"}
