[project]
name = "mk64"
version = "1.0.0"
description = "Mario Kart 64 is the original 3D kart racing game. Collect and fire off items, maneuver around hazards, execute drifts and mini-turbos, risk shortcuts but stay on the track, and race to victory in each course and cup."
authors = [
    {name = "Edsploration"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mk64.WorldClass" = "mk64.Register:WORLD_CLASS"
"mk64.WebWorldClass" = "mk64.Register:WEB_WORLD_CLASS"
"mk64.Client" = "mk64.Register:CLIENT_FUNCTION"
