from BaseClasses import Item, ItemClassification
from .Locations import shop_locations_table, loc_Post_Cloud, loc_Moon_Post_Moon


class SMOItem(Item):
    game: str = "Super Mario Odyssey"

    def __init__(self, name: str, classification: ItemClassification, player: int, id: int):
        super().__init__(name, classification, id, player)


# def create_event(self, event: str) -> SMOItem:
#     return SMOItem(event, ItemClassification.progression, self.player, None)

moon_types = {
    "Cap Power Moon": 1,
    "Cascade Power Moon": 2,
    "Sand Power Moon": 3,
    "Wooded Power Moon": 4,
    "Lake Power Moon": 5,
    "Cloud Power Moon": 6,
    "Lost Power Moon": 7,
    "Metro Power Moon": 8,
    "Seaside Power Moon": 9,
    "Snow Power Moon": 10,
    "Luncheon Power Moon": 11,
    "Ruined Power Moon": 12,
    "Bowser Power Moon": 13,
    "Moon Power Moon": 14,
    "Power Star": 15,
    "Dark Side Power Moon": 16,
    "Darker Side Multi-Moon": 17,
    "Cascade Story Moon": 18,
    "Sand Story Moon": 19,
    "Wooded Story Moon": 20,
    "Metro Story Moon": 21,
    "Seaside Story Moon": 22,
    "Snow Story Moon": 23,
    "Luncheon Story Moon": 24,
    "Bowser Story Moon": 25,
    "Cascade Multi-Moon": 26,
    "Sand Multi-Moon": 27,
    "Wooded Multi-Moon": 28,
    "Lake Multi-Moon": 29,
    "Metro Multi-Moon": 30,
    "Seaside Multi-Moon": 31,
    "Snow Multi-Moon": 32,
    "Luncheon Multi-Moon": 33,
    "Ruined Multi-Moon": 34,
    "Bowser Multi-Moon": 35,
    "Mushroom Multi-Moon": 36,
    "Dark Side Multi-Moon": 38,
}

moon_item_table = {
    # **Cap,
    # **Cascade,
    # **Sand,
    # **Lake,
    # **Wooded,
    # **Cloud,
    # **Lost,
    # **Metro,
    # **Snow,
    # **Seaside,
    # **Luncheon,
    # **Ruined,
    # **Bowser,
    # **Moon,
    # **Mushroom,
    # **Dark,
    # **Darker,
    #**moon_types,
    **loc_Post_Cloud,
    **loc_Moon_Post_Moon,
    **shop_locations_table
}

multi_moons = {
    "Cascade" : ["Multi Moon Atop the Falls"],
    "Sand" : ["Showdown on the Inverted Pyramid",
    "The Hole in the Desert"],
    "Lake" : ["Broodals Over the Lake"],
    "Wooded" : ["Flower Thieves of Sky Garden",
    "Defend the Secret Flower Field!"],
    "Metro" : ["New Donk City's Pest Problem",
    "A Traditional Festival!"],
    "Snow" : ["The Bound Bowl Grand Prix"],
    "Seaside" : ["The Glass Is Half Full!"],
    "Luncheon" : ["Big Pot on the Volcano: Dive In!",
    "Cookatiel Showdown!"],
    "Ruined" : ["Battle with the Lord of Lightning!"],
    "Bowser" : ["Showdown at Bowser's Castle"],
    "Mushroom" : ["Tussle in Tostarena: Rematch",
    "Struggle in Steam Gardens: Rematch",
    "Dust-Up in New Donk City: Rematch",
    "Battle in Bubblaine: Rematch",
    "Blowup at Mount Volbono: Rematch",
    "Rumble in Crumbleden: Rematch"],
    "Dark" : ["Arrival at Rabbit Ridge!"],
    "Darker" : ["A Long Journey's End!"]
}

story_moons = {
    "Cascade" : ["Our First Power Moon"],
    "Sand" : ["Atop the Highest Tower",
    "Moon Shards in the Sand"],
    "Wooded" : ["Road to Sky Garden",
    "Path to the Secret Flower Field"],
    "Metro" : ["Drummer on Board!",
    "Guitarist on Board!",
    "Bassist on Board!",
    "Trumpeter on Board!",
    "Powering Up the Station"],
    "Snow" : ["The Icicle Barrier",
    "The Ice Wall Barrier",
    "The Gusty Barrier",
    "The Snowy Mountain Barrier"],
    "Seaside" : ["The Stone Pillar Seal",
    "The Lighthouse Seal",
    "The Hot Spring Seal",
    "The Seal Above the Canyon"],
    "Luncheon" : ["The Broodals Are After Some Cookin'",
    "Under the Cheese Rocks",
    "Climb Up the Cascading Magma"],
    "Bowser" : ["Infiltrate Bowser's Castle!",
    "Smart Bombing",
    "Big Broodal Battle"]
}

outfits = [
    "Sombrero",
    "Poncho",
    "Skeleton Suit",
    "Boxer Shorts",
    "Swim Goggles",
    "Swimwear",
    "Explorer Hat",
    "Explorer Outfit",
    "Builder Helmet",
    "Builder Outfit",
    "Snow Hood",
    "Snow Suit",
    "Resort Hat",
    "Resort Outfit",
    "Chef Hat",
    "Chef Suit",
    "Samurai Helmet",
    "Samurai Armor",
    "Caveman Headwear",
    "Caveman Outfit",
    "Cowboy Hat",
    "Cowboy Outfit",
    "Space Helmet",
    "Space Suit",
    "Pirate Hat",
    "Pirate Outfit",
    "Clown Hat",
    "Clown Suit",
    "Doctor Headwear",
    "Doctor Outfit",
    "Mechanic Cap",
    "Mechanic Outfit",
    "Mario 64 Cap",
    "Mario 64 Suit",
    "Metal Mario Cap",
    "Metal Mario Suit",
    "Captain's Hat",
    "Mario's Top Hat",
    "Mario's Tuxedo",
    "Black Top Hat",
    "Black Tuxedo",
    "Scientist Visor",
    "Scientist Outfit",
    "Aviator Cap",
    "Aviator Outfit",
    "Golf Cap",
    "Golf Outfit",
    "Sailor Hat",
    "Sailor Suit",
    "Painter's Cap",
    "Painter Outfit",
    "Happi Headband",
    "Happi Outfit",
    "Employee Cap",
    "Employee Uniform",
    "Fashionable Cap",
    "Fashionable Outfit",
    "Black Fedora",
    "Black Suit",
    "Football Helmet",
    "Football Uniform",
    "Classic Cap",
    "Classic Suit",
    "Luigi Cap",
    "Luigi Suit",
    "Waluigi Cap",
    "Waluigi Suit",
    "Diddy Kong Hat",
    "Diddy Kong Suit",
    "Wario Cap",
    "Wario Suit",
    "Hakama",
    "Bowser's Top Hat",
    "Bowser's Tuxedo",
    "Bridal Veil",
    "Bridal Gown",
    "Gold Mario Cap",
    "Gold Mario Suit",
    "King's Crown",
    "King's Outfit",
    "Invisibility Hat"
]

# Technically filler until achievements implemented
shop_items = [
    "Cap Kingdom Sticker",
    "Cascade Kingdom Sticker",
    "Sand Kingdom Sticker",
    "Lake Kingdom Sticker",
    "Wooded Kingdom Sticker",
    "Lost Kingdom Sticker",
    "Metro Kingdom Sticker",
    "Snow Kingdom Sticker",
    "Seaside Kingdom Sticker",
    "Luncheon Kingdom Sticker",
    "Bowser's Kingdom Sticker",
    "Moon Kingdom Sticker",
    "Pipe Sticker",
    "Coin Sticker",
    "Block Sticker",
    "? Block Sticker",
    "Mushroom Kingdom Sticker",
    "Plush Frog",
    "Bonneton Tower Model",
    "T-Rex Model",
    "Triceratops Trophy",
    "Inverted Pyramid Model",
    "Jaxi Statue",
    "Underwater Dome",
    "Rubber Dorrie",
    "Flowers from Steam Gardens",
    "Steam Gardener Watering Can",
    "Potted Palm Tree",
    "Butterfly Mobile",
    "Pauline Statue",
    "New Donk City Hall Model",
    "Shiverian Rug",
    "Shiverian Nesting Dolls",
    "Sand Jar",
    "Glass Tower Model",
    "Souvenir Forks",
    "Vegetable Plate",
    "Paper Lantern",
    "Jizo Statue",
    "Moon Rock Fragment",
    "Moon Lamp",
    "Mushroom Cushion Set",
    "Peach's Castle Model"
]

world_list = [
    "Cap",
    "Cascade",
    "Sand",
    "Lake",
    "Wooded",
    "Cloud",
    "Lost",
    "Metro",
    "Snow",
    "Seaside",
    "Luncheon",
    "Ruined",
    "Bowser",
    "Moon",
    "Mushroom",
    "Dark",
    "Darker"
]

filler_item_table = {
    "50 Coins": 9994,
    "100 Coins": 9995,
    "250 Coins": 9996,
    "500 Coins": 9997,
    "1000 Coins": 9998
}

item_table = {
    **moon_item_table,
    # **world_items_table,
    **filler_item_table
}

# moon_item_list = [
#     *list(Cap.keys()),
#     *list(Cascade.keys()),
#     *list(Sand.keys()),
#     *list(Lake.keys()),
#     *list(Wooded.keys()),
#     *list(Cloud.keys()),
#     *list(Lost.keys()),
#     *list(Metro.keys()),
#     *list(Snow.keys()),
#     *list(Seaside.keys()),
#     *list(Luncheon.keys()),
#     *list(Ruined.keys()),
#     *list(Bowser.keys()),
#     *list(Moon.keys()),
#     *list(Mushroom.keys()),
#     *list(Dark.keys()),
#     *list(Darker.keys())
# ]
