[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "smo"
dynamic = ["version"]
description = "Super Mario Odyssey"
authors = [
    {name = "Kgamer77"}
]
license = "MIT AND (Apache-2.0 AND (GPL-3.0-or-later))"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"smo.WorldClass" = "smo.Register:WORLD_CLASS"
"smo.WebWorldClass" = "smo.Register:WEB_WORLD_CLASS"
"smo.Client" = "smo.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "smo.Register:VERSION"}
