[project]
name = "smo"
version = "1.0.0"
description = "Super Mario Odyssey is a 3-D Platformer where Mario sets off across the world with his companion Cappy to save Princess Peach and Cappy's sister Tiara from Bowser's wedding plans."
authors = [
    {name = "Kgamer77"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"smo.WorldClass" = "smo.Register:WORLD_CLASS"
"smo.WebWorldClass" = "smo.Register:WEB_WORLD_CLASS"
"smo.Client" = "smo.Register:CLIENT_FUNCTION"
