[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "toontown"
dynamic = ["version"]
description = "Toontown"
authors = [
    {name = "DevvyDont"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"toontown.WorldClass" = "toontown.Register:WORLD_CLASS"
"toontown.WebWorldClass" = "toontown.Register:WEB_WORLD_CLASS"
"toontown.Client" = "toontown.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "toontown.Register:VERSION"}
