[project]
name = "toontown"
version = "1.0.0"
description = "Toontown is a now defunct classic Disney MMORPG where you play as "toons" to fend off evil robots from invading the tooniverse with the use of "gags" since they mean business and cannot take a joke."
authors = [
    {name = "DevvyDont"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"toontown.WorldClass" = "toontown.Register:WORLD_CLASS"
"toontown.WebWorldClass" = "toontown.Register:WEB_WORLD_CLASS"
"toontown.Client" = "toontown.Register:CLIENT_FUNCTION"
