[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "paint"
dynamic = ["version"]
description = "Paint"
authors = [
    {name = "MairoManTAW"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"paint.WorldClass" = "paint.Register:WORLD_CLASS"
"paint.WebWorldClass" = "paint.Register:WEB_WORLD_CLASS"
"paint.Client" = "paint.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["paint*", "paint"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "paint.Constants.VERSION"}
