[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "wordipelago"
dynamic = ["version"]
description = "Wordipelago"
authors = [
    {name = "ProfDeCube"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"wordipelago.WorldClass" = "wordipelago.Register:WORLD_CLASS"
"wordipelago.WebWorldClass" = "wordipelago.Register:WEB_WORLD_CLASS"
"wordipelago.Client" = "wordipelago.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
