[project]
name = "wargroove"
version = "1.0.0"
description = "Command an army, in this retro style turn based strategy game!"
authors = [
    {name = "FlySniper"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"wargroove.WorldClass" = "wargroove.Register:WORLD_CLASS"
"wargroove.WebWorldClass" = "wargroove.Register:WEB_WORLD_CLASS"
"wargroove.Client" = "wargroove.Register:CLIENT_FUNCTION"
