[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mzm"
dynamic = ["version"]
description = "MultiWorld: Metroid Zero Mission"
authors = [
    {name = "Noise"}
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mzm.WorldClass" = "mzm.Register:WORLD_CLASS"
"mzm.WebWorldClass" = "mzm.Register:WEB_WORLD_CLASS"
"mzm.Client" = "mzm.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["mzm*", "mzm"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "mzm.Constants.VERSION"}
