[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "stardew_valley"
dynamic = ["version"]
description = "Stardew Valley"
authors = [
    {name = "Kaito Kid"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"stardew_valley.WorldClass" = "stardew_valley.Register:WORLD_CLASS"
"stardew_valley.WebWorldClass" = "stardew_valley.Register:WEB_WORLD_CLASS"
"stardew_valley.Client" = "stardew_valley.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["test*", "test"]
include = ["stardew_valley*", "stardew_valley"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "stardew_valley.Constants.VERSION"}
