[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kdl3"
dynamic = ["version"]
description = "Kirby"
authors = [
    {name = "Silvris"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"kdl3.WorldClass" = "kdl3.Register:WORLD_CLASS"
"kdl3.WebWorldClass" = "kdl3.Register:WEB_WORLD_CLASS"
"kdl3.Client" = "kdl3.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
