#define IniFile SourcePath + "\setup.ini"
#define source_path_relative ReadIni(IniFile, "Data", "source_path", "build\exe.win-amd64-3.13")
#define source_path AddBackslash(SourcePath) + source_path_relative
#define min_windows ReadIni(IniFile, "Data", "min_windows", "")

#pragma message "IniFile: " + IniFile
#pragma message "SourcePath: " + SourcePath
#pragma message "source_path_relative: " + source_path_relative
#pragma message "source_path: " + source_path

#define MyAppName "MultiworldGG-Test"
#define MyAppExeName "MultiworldGG.exe"
#define MyAppIcon "data/icon.ico"
#dim VersionTuple[4]
#define MyAppVersion GetVersionComponents(source_path + '\MultiworldGG.exe', VersionTuple[0], VersionTuple[1], VersionTuple[2], VersionTuple[3])
#define MyAppVersionText ReadIni(SourcePath + "\setup.ini", "Data", "app_version", "0.8.0b7")
#pragma message "MyAppVersionText: " + MyAppVersionText

; BEGIN AUTOGEN: in_client (regenerated by tools/regen_inno_components.py from mwgg_igdb_sixteen)
#define InClientDescriptions ""
; END AUTOGEN: in_client

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
AppId={{918BA46A-FAB8-460C-9DFF-AE691E1C865E}}
AppName={#MyAppName}
AppCopyright=Distributed under GPLv3 License
AppVerName={#MyAppName} {#MyAppVersionText}
VersionInfoVersion={#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=no
DisableProgramGroupPage=yes
DefaultGroupName=MultiworldGG-Test
OutputDir=setups
OutputBaseFilename=Setup {#MyAppName} {#MyAppVersionText}
Compression=lzma2
SolidCompression=yes
LZMANumBlockThreads=8
ArchitecturesInstallIn64BitMode=x64compatible arm64
ChangesAssociations=yes
ArchitecturesAllowed=x64compatible arm64
AllowNoIcons=yes
SetupIconFile={#MyAppIcon}
UninstallDisplayIcon={app}\{#MyAppExeName}
LicenseFile=docs\combined_license_inno.txt
WizardStyle= modern
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}";

[Types]
Name: "minimal"; Description: "Minimal installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom
Name: "full"; Description: "Full installation"

[Components]
; BEGIN AUTOGEN: components (regenerated by tools/regen_inno_components.py from mwgg_igdb_sixteen)
Name: "against_the_storm"; Description: "Against the Storm"; ExtraDiskSpaceRequired: 182_953
Name: "ahit"; Description: "A Hat in Time"; ExtraDiskSpaceRequired: 610_238
Name: "albw"; Description: "A Link Between Worlds"; ExtraDiskSpaceRequired: 310_433
Name: "alttp"; Description: "A Link to the Past"; ExtraDiskSpaceRequired: 4_013_629
Name: "animal_well"; Description: "Animal Well"; ExtraDiskSpaceRequired: 644_488
Name: "apeescape"; Description: "Ape Escape"; ExtraDiskSpaceRequired: 2_262_141
Name: "apgo"; Description: "apgo"; ExtraDiskSpaceRequired: 0
Name: "apquest"; Description: "apquest"; ExtraDiskSpaceRequired: 0
Name: "apsudoku"; Description: "apsudoku"; ExtraDiskSpaceRequired: 0
Name: "archipidle"; Description: "archipidle"; ExtraDiskSpaceRequired: 0
Name: "balatro"; Description: "Balatro"; ExtraDiskSpaceRequired: 175_457
Name: "banjo_tooie"; Description: "Banjo Tooie"; ExtraDiskSpaceRequired: 4_345_321
Name: "bfbb"; Description: "bfbb"; ExtraDiskSpaceRequired: 0
Name: "blasphemous"; Description: "blasphemous"; ExtraDiskSpaceRequired: 0
Name: "bomb_rush_cyberfunk"; Description: "Bomb Rush Cyberfunk"; ExtraDiskSpaceRequired: 357_946
Name: "brotato"; Description: "Brotato"; ExtraDiskSpaceRequired: 241_712
Name: "cat_quest"; Description: "Cat Quest"; ExtraDiskSpaceRequired: 59_720
Name: "cccharles"; Description: "cccharles"; ExtraDiskSpaceRequired: 0
Name: "celeste"; Description: "Celeste"; ExtraDiskSpaceRequired: 193_688
Name: "celeste_open_world"; Description: "Celeste Open World"; ExtraDiskSpaceRequired: 4_928_448
Name: "chainedechoes"; Description: "chainedechoes"; ExtraDiskSpaceRequired: 0
Name: "chatipelago"; Description: "chatipelago"; ExtraDiskSpaceRequired: 0
Name: "checksfinder"; Description: "checksfinder"; ExtraDiskSpaceRequired: 0
Name: "civ_6"; Description: "Civilization VI"; ExtraDiskSpaceRequired: 446_986
Name: "clique"; Description: "clique"; ExtraDiskSpaceRequired: 0
Name: "crosscode"; Description: "CrossCode"; ExtraDiskSpaceRequired: 2_160_529
Name: "crystal_project"; Description: "Crystal Project"; ExtraDiskSpaceRequired: 1_409_535
Name: "ctjot"; Description: "CT Journey of Time"; ExtraDiskSpaceRequired: 167_345
Name: "cuphead"; Description: "Cuphead"; ExtraDiskSpaceRequired: 1_048_162
Name: "cv64"; Description: "Castlevania 64"; ExtraDiskSpaceRequired: 913_776
Name: "cv_dos"; Description: "cv_dos"; ExtraDiskSpaceRequired: 0
Name: "cvcotm"; Description: "Castlevania Circle of the Moon"; ExtraDiskSpaceRequired: 794_243
Name: "dark_souls_2"; Description: "dark_souls_2"; ExtraDiskSpaceRequired: 0
Name: "dark_souls_3"; Description: "dark_souls_3"; ExtraDiskSpaceRequired: 0
Name: "diddy_kong_racing"; Description: "Diddy Kong Racing"; ExtraDiskSpaceRequired: 261_037
Name: "dk64"; Description: "Donkey Kong 64"; ExtraDiskSpaceRequired: 38_933_451
Name: "dkc"; Description: "Donkey Kong Country"; ExtraDiskSpaceRequired: 1_008_054
Name: "dkc2"; Description: "Donkey Kong Country 2"; ExtraDiskSpaceRequired: 2_293_435
Name: "dontstarvetogether"; Description: "Don't Starve Together"; ExtraDiskSpaceRequired: 759_437
Name: "doom_1993"; Description: "doom_1993"; ExtraDiskSpaceRequired: 0
Name: "doom_ii"; Description: "doom_ii"; ExtraDiskSpaceRequired: 0
Name: "doronko_wanko"; Description: "Doronko Wanko"; ExtraDiskSpaceRequired: 54_471
Name: "dredge"; Description: "Dredge"; ExtraDiskSpaceRequired: 124_668
Name: "dsr"; Description: "dsr"; ExtraDiskSpaceRequired: 0
Name: "dw1"; Description: "Dragon Warrior"; ExtraDiskSpaceRequired: 190_139
Name: "earthbound"; Description: "Earthbound"; ExtraDiskSpaceRequired: 2_587_999
Name: "enderlilies"; Description: "Ender Lilies"; ExtraDiskSpaceRequired: 1_483_829
Name: "factorio"; Description: "Factorio"; ExtraDiskSpaceRequired: 1_044_588
Name: "factorio_saws"; Description: "factorio_saws"; ExtraDiskSpaceRequired: 0
Name: "faxanadu"; Description: "Faxanadu"; ExtraDiskSpaceRequired: 98_209
Name: "ff1"; Description: "Final Fantasy I"; ExtraDiskSpaceRequired: 93_036
Name: "ff4fe"; Description: "Final Fantasy IV Free Enterprise"; ExtraDiskSpaceRequired: 1_484_278
Name: "ffmq"; Description: "Final Fantasy Mystic Quest"; ExtraDiskSpaceRequired: 513_688
Name: "ffta"; Description: "Final Fantasy Tactics Advance"; ExtraDiskSpaceRequired: 1_056_544
Name: "fm"; Description: "Yu-Gi-Oh! Forbidden Memories"; ExtraDiskSpaceRequired: 1_399_547
Name: "getting_over_it"; Description: "Getting Over It"; ExtraDiskSpaceRequired: 29_455
Name: "gstla"; Description: "Golden Sun: The Lost Age"; ExtraDiskSpaceRequired: 2_493_105
Name: "hades"; Description: "Hades"; ExtraDiskSpaceRequired: 274_213
Name: "hcniko"; Description: "HC Niko"; ExtraDiskSpaceRequired: 1_156_820
Name: "hk"; Description: "Hollow Knight"; ExtraDiskSpaceRequired: 2_190_871
Name: "into_the_breach"; Description: "into_the_breach"; ExtraDiskSpaceRequired: 0
Name: "jakanddaxter"; Description: "Jak and Daxter"; ExtraDiskSpaceRequired: 668_917
Name: "jigsaw"; Description: "jigsaw"; ExtraDiskSpaceRequired: 0
Name: "k64"; Description: "Kirby 64"; ExtraDiskSpaceRequired: 296_419
Name: "kdl3"; Description: "Kirby's Dream Land 3"; ExtraDiskSpaceRequired: 1_088_257
Name: "kh1"; Description: "Kingdom Hearts"; ExtraDiskSpaceRequired: 945_036
Name: "kh2"; Description: "Kingdom Hearts II"; ExtraDiskSpaceRequired: 1_488_039
Name: "landstalker"; Description: "Landstalker"; ExtraDiskSpaceRequired: 406_358
Name: "lego_star_wars_tcs"; Description: "LEGO Star Wars: The Complete Saga"; ExtraDiskSpaceRequired: 850_576
Name: "lufia2ac"; Description: "Lufia II Ancient Cave"; ExtraDiskSpaceRequired: 413_492
Name: "luigismansion"; Description: "Luigi's Mansion"; ExtraDiskSpaceRequired: 1_297_891
Name: "mario_kart_double_dash"; Description: "Mario Kart: Double Dash!!"; ExtraDiskSpaceRequired: 214_378
Name: "marioland2"; Description: "Super Mario Land 2"; ExtraDiskSpaceRequired: 416_677
Name: "megamix"; Description: "Megamix"; ExtraDiskSpaceRequired: 242_687
Name: "messenger"; Description: "The Messenger"; ExtraDiskSpaceRequired: 521_544
Name: "metroidfusion"; Description: "Metroid Fusion"; ExtraDiskSpaceRequired: 1_960_796
Name: "metroidprime"; Description: "Metroid Prime"; ExtraDiskSpaceRequired: 23_480_868
Name: "minecraft"; Description: "Minecraft"; ExtraDiskSpaceRequired: 555_926
Name: "mk64"; Description: "Mario Kart 64"; ExtraDiskSpaceRequired: 366_034
Name: "mlss"; Description: "Mario & Luigi: Superstar Saga"; ExtraDiskSpaceRequired: 886_952
Name: "mm2"; Description: "Mega Man 2"; ExtraDiskSpaceRequired: 321_918
Name: "mm3"; Description: "Mega Man 3"; ExtraDiskSpaceRequired: 318_372
Name: "mm_recomp"; Description: "Majora's Mask Recompiled"; ExtraDiskSpaceRequired: 698_897
Name: "mmbn3"; Description: "Mega Man Battle Network 3"; ExtraDiskSpaceRequired: 542_094
Name: "mmx3"; Description: "Mega Man X3"; ExtraDiskSpaceRequired: 627_894
Name: "momodoramoonlitfarewell"; Description: "Momodora: Moonlit Farewell"; ExtraDiskSpaceRequired: 125_946
Name: "monster_sanctuary"; Description: "Monster Sanctuary"; ExtraDiskSpaceRequired: 2_403_887
Name: "musedash"; Description: "Muse Dash"; ExtraDiskSpaceRequired: 290_905
Name: "mzm"; Description: "Metroid Zero Mission"; ExtraDiskSpaceRequired: 685_806
Name: "nine_sols"; Description: "nine_sols"; ExtraDiskSpaceRequired: 0
Name: "oot"; Description: "Ocarina of Time"; ExtraDiskSpaceRequired: 5_047_802
Name: "ori_wotw"; Description: "ori_wotw"; ExtraDiskSpaceRequired: 0
Name: "oribf"; Description: "Ori and the Blind Forest"; ExtraDiskSpaceRequired: 413_242
Name: "osrs"; Description: "osrs"; ExtraDiskSpaceRequired: 0
Name: "outer_wilds"; Description: "Outer Wilds"; ExtraDiskSpaceRequired: 649_509
Name: "overcooked2"; Description: "Overcooked 2"; ExtraDiskSpaceRequired: 300_159
Name: "paint"; Description: "paint"; ExtraDiskSpaceRequired: 0
Name: "papermario"; Description: "Paper Mario 64"; ExtraDiskSpaceRequired: 3_424_893
Name: "phoa"; Description: "phoa"; ExtraDiskSpaceRequired: 0
Name: "placidplasticducksim"; Description: "Placid Plastic Duck Simulator"; ExtraDiskSpaceRequired: 19_149
Name: "pmd_eos"; Description: "Pokemon Mystery Dungeon: Explorers of Sky"; ExtraDiskSpaceRequired: 1_377_055
Name: "pokemon_crystal"; Description: "Pokemon Crystal"; ExtraDiskSpaceRequired: 2_872_323
Name: "pokemon_emerald"; Description: "Pokemon Emerald"; ExtraDiskSpaceRequired: 2_556_819
Name: "pokemon_frlg"; Description: "Pokemon FireRed/LeafGreen"; ExtraDiskSpaceRequired: 4_742_792
Name: "pokemon_rb"; Description: "Pokemon Red/Blue"; ExtraDiskSpaceRequired: 1_936_425
Name: "powerwashsimulator"; Description: "PowerWash Simulator"; ExtraDiskSpaceRequired: 619_444
Name: "quake"; Description: "quake"; ExtraDiskSpaceRequired: 0
Name: "rabi_ribi"; Description: "rabi_ribi"; ExtraDiskSpaceRequired: 0
Name: "rac2"; Description: "Ratchet & Clank 2"; ExtraDiskSpaceRequired: 531_970
Name: "raft"; Description: "Raft"; ExtraDiskSpaceRequired: 130_517
Name: "refunct"; Description: "refunct"; ExtraDiskSpaceRequired: 0
Name: "rimworld"; Description: "rimworld"; ExtraDiskSpaceRequired: 0
Name: "rogue_legacy"; Description: "Rogue Legacy"; ExtraDiskSpaceRequired: 130_942
Name: "ror1"; Description: "Risk of Rain"; ExtraDiskSpaceRequired: 88_077
Name: "ror2"; Description: "Risk of Rain 2"; ExtraDiskSpaceRequired: 196_735
Name: "rotn"; Description: "rotn"; ExtraDiskSpaceRequired: 0
Name: "sa2b"; Description: "Sonic Adventure 2: Battle"; ExtraDiskSpaceRequired: 2_003_849
Name: "sadx"; Description: "Sonic Adventure DX"; ExtraDiskSpaceRequired: 4_225_799
Name: "satisfactory"; Description: "Satisfactory"; ExtraDiskSpaceRequired: 555_598
Name: "sc2"; Description: "sc2"; ExtraDiskSpaceRequired: 0
Name: "seaofthieves"; Description: "Sea of Thieves"; ExtraDiskSpaceRequired: 10_213_401
Name: "shivers"; Description: "Shivers"; ExtraDiskSpaceRequired: 164_889
Name: "shorthike"; Description: "A Short Hike"; ExtraDiskSpaceRequired: 110_942
Name: "simpsonshitnrun"; Description: "simpsonshitnrun"; ExtraDiskSpaceRequired: 0
Name: "sims4"; Description: "The Sims 4"; ExtraDiskSpaceRequired: 771_131
Name: "sly1"; Description: "Sly Cooper"; ExtraDiskSpaceRequired: 191_602
Name: "sm"; Description: "Super Metroid"; ExtraDiskSpaceRequired: 2_046_122
Name: "sm64ex"; Description: "Super Mario 64 (Port)"; ExtraDiskSpaceRequired: 176_915
Name: "sm64hacks"; Description: "Super Mario 64 (Hacks)"; ExtraDiskSpaceRequired: 782_500
Name: "sm_map_rando"; Description: "Super Metroid Map Rando"; ExtraDiskSpaceRequired: 45_685_867
Name: "smo"; Description: "Super Mario Odyssey"; ExtraDiskSpaceRequired: 3_788_511
Name: "sms"; Description: "Super Mario Sunshine"; ExtraDiskSpaceRequired: 159_636
Name: "smw"; Description: "Super Mario World"; ExtraDiskSpaceRequired: 2_225_312
Name: "soe"; Description: "Secret of Evermore"; ExtraDiskSpaceRequired: 243_401
Name: "sonic_heroes"; Description: "Sonic Heroes"; ExtraDiskSpaceRequired: 1_175_567
Name: "sotn"; Description: "Castlevania: Symphony of the Night"; ExtraDiskSpaceRequired: 1_591_279
Name: "spyro3"; Description: "Spyro 3"; ExtraDiskSpaceRequired: 561_700
Name: "ss"; Description: "Skyward Sword"; ExtraDiskSpaceRequired: 1_306_049
Name: "star_fox_64"; Description: "Star Fox 64"; ExtraDiskSpaceRequired: 220_672
Name: "stardew_valley"; Description: "Stardew Valley"; ExtraDiskSpaceRequired: 6_087_576
Name: "subnautica"; Description: "Subnautica"; ExtraDiskSpaceRequired: 157_606
Name: "swr"; Description: "Star Wars: Racer"; ExtraDiskSpaceRequired: 120_281
Name: "tboir"; Description: "tboir"; ExtraDiskSpaceRequired: 0
Name: "terraria"; Description: "Terraria"; ExtraDiskSpaceRequired: 163_951
Name: "tetrisattack"; Description: "Tetris Attack"; ExtraDiskSpaceRequired: 387_967
Name: "timespinner"; Description: "Timespinner"; ExtraDiskSpaceRequired: 509_798
Name: "tloz"; Description: "The Legend of Zelda"; ExtraDiskSpaceRequired: 252_548
Name: "tloz_ooa"; Description: "Oracle of Ages"; ExtraDiskSpaceRequired: 809_597
Name: "tloz_oos"; Description: "Oracle of Seasons"; ExtraDiskSpaceRequired: 1_301_906
Name: "tloz_ph"; Description: "Phantom Hourglass"; ExtraDiskSpaceRequired: 1_263_666
Name: "tmc"; Description: "The Minish Cap"; ExtraDiskSpaceRequired: 994_122
Name: "toontown"; Description: "Toontown"; ExtraDiskSpaceRequired: 905_891
Name: "tp"; Description: "Twilight Princess"; ExtraDiskSpaceRequired: 1_985_086
Name: "trackmania"; Description: "Trackmania"; ExtraDiskSpaceRequired: 105_190
Name: "tunic"; Description: "TUNIC"; ExtraDiskSpaceRequired: 2_861_231
Name: "tww"; Description: "The Wind Waker"; ExtraDiskSpaceRequired: 1_003_684
Name: "tyrian"; Description: "Tyrian"; ExtraDiskSpaceRequired: 813_836
Name: "ufo50"; Description: "ufo50"; ExtraDiskSpaceRequired: 0
Name: "undertale"; Description: "Undertale"; ExtraDiskSpaceRequired: 705_555
Name: "v6"; Description: "V6"; ExtraDiskSpaceRequired: 34_013
Name: "waffles"; Description: "waffles"; ExtraDiskSpaceRequired: 0
Name: "wargroove"; Description: "Wargroove"; ExtraDiskSpaceRequired: 807_667
Name: "wargroove2"; Description: "Wargroove 2"; ExtraDiskSpaceRequired: 5_966_418
Name: "witness"; Description: "The Witness"; ExtraDiskSpaceRequired: 1_035_025
Name: "wl"; Description: "Wario Land"; ExtraDiskSpaceRequired: 718_704
Name: "wl4"; Description: "Wario Land 4"; ExtraDiskSpaceRequired: 390_328
Name: "wordipelago"; Description: "wordipelago"; ExtraDiskSpaceRequired: 0
Name: "xenobladex"; Description: "Xenoblade Chronicles X"; ExtraDiskSpaceRequired: 3_105_011
Name: "yachtdice"; Description: "yachtdice"; ExtraDiskSpaceRequired: 0
Name: "yoshisisland"; Description: "Yoshi's Island"; ExtraDiskSpaceRequired: 725_033
Name: "yugioh06"; Description: "Yu-Gi-Oh! 2006"; ExtraDiskSpaceRequired: 344_344
Name: "yugiohddm"; Description: "Yu-Gi-Oh! Dungeon Dice Monsters"; ExtraDiskSpaceRequired: 130_587
Name: "zelda2"; Description: "Zelda II"; ExtraDiskSpaceRequired: 242_982
Name: "zork_grand_inquisitor"; Description: "zork_grand_inquisitor"; ExtraDiskSpaceRequired: 0
; END AUTOGEN: components

[Dirs]
NAME: "{app}"; Flags: setntfscompression; Permissions: everyone-modify users-modify authusers-modify;

[Files]
Source: "{#source_path}\*"; Excludes: "*.sfc, *.log, SNI, EnemizerCLI"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName} Folder"; Filename: "{app}";
Name: "{group}\{#MyAppName} Launcher"; Filename: "{app}\MultiworldGG.exe"

Name: "{commondesktop}\{#MyAppName} Folder"; Filename: "{app}"; Tasks: desktopicon
Name: "{commondesktop}\{#MyAppName} Launcher"; Filename: "{app}\MultiworldGG.exe"; Tasks: desktopicon

[Run]

; Install uv if not already on PATH. Order matters: winget first (preferred, integrates with
; user's package manager so they can `winget upgrade astral-sh.uv` later); fall back to astral's
; PowerShell installer on systems without winget (older Win10, some corporate images).
Filename: "winget"; Parameters: "install --id=astral-sh.uv -e --accept-source-agreements --accept-package-agreements"; Check: IsUvNeededViaWinget; StatusMsg: "Installing uv via winget..."; Flags: runhidden
Filename: "powershell.exe"; Parameters: "-ExecutionPolicy ByPass -Command ""irm https://astral.sh/uv/install.ps1 | iex"""; Check: IsUvNeededViaPwsh; StatusMsg: "Installing uv via astral installer..."; Flags: runhidden

Filename: "{app}\MultiworldGG"; Parameters: "--update-modules --worlds {code:GetSelectedWorld}"; StatusMsg: "Updating modules..."; Flags: runasoriginaluser runhidden
; Filename: "{app}\MultiworldGG"; Description: "{cm:LaunchProgram,{#StringChange('Launcher', '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; Silent install from updater auto starts the launcher again
; Filename: "{app}\MultiworldGG"; StatusMsg: "MultiworldGG ... done"; Flags: nowait skipifnotsilent


[UninstallDelete]
Type: dirifempty; Name: "{app}"

[InstallDelete]
Type: files; Name: "{app}\*.exe"

[Registry]


Root: HKCR; Subkey: ".aplttp";                                    ValueData: "{#MyAppName}alttppatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}alttppatch";                     ValueData: "MultiworldGG A Link to the Past Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}alttppatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}alttppatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";         ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apsm";                                     ValueData: "{#MyAppName}smpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smpatch";                       ValueData: "MultiworldGG Super Metroid Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smpatch\DefaultIcon";           ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smpatch\shell\open\command";    ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apdkc3";                                   ValueData: "{#MyAppName}dkc3patch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkc3patch";                     ValueData: "MultiworldGG Donkey Kong Country 3 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkc3patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkc3patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".aptatk";                                   ValueData: "{#MyAppName}tatkpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}tatkpatch";                     ValueData: "MultiworldGG Tetris Attack Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}tatkpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}tatkpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apsmw";                                    ValueData: "{#MyAppName}smwpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smwpatch";                      ValueData: "MultiworldGG Super Mario World Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smwpatch\DefaultIcon";          ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smwpatch\shell\open\command";   ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apzl";                                     ValueData: "{#MyAppName}zlpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}zlpatch";                       ValueData: "MultiworldGG Zillion Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}zlpatch\DefaultIcon";           ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}zlpatch\shell\open\command";    ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apsmz3";                                   ValueData: "{#MyAppName}smz3patch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smz3patch";                     ValueData: "MultiworldGG SMZ3 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smz3patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smz3patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apsoe";                                    ValueData: "{#MyAppName}soepatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}soepatch";                      ValueData: "MultiworldGG Secret of Evermore Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}soepatch\DefaultIcon";          ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}soepatch\shell\open\command";   ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apl2ac";                                   ValueData: "{#MyAppName}l2acpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}l2acpatch";                     ValueData: "MultiworldGG Lufia II Ancient Cave Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}l2acpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}l2acpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apkdl3";                                   ValueData: "{#MyAppName}kdl3patch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}kdl3patch";                     ValueData: "MultiworldGG Kirby's Dream Land 3 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}kdl3patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}kdl3patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apmc";                                     ValueData: "{#MyAppName}mcdata";         Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mcdata";                        ValueData: "MultiworldGG Minecraft Data"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mcdata\DefaultIcon";            ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mcdata\shell\open\command";     ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apz5";                                     ValueData: "{#MyAppName}n64zpf";         Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}n64zpf";                        ValueData: "MultiworldGG Ocarina of Time Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}n64zpf\DefaultIcon";            ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}n64zpf\shell\open\command";     ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apred";                                    ValueData: "{#MyAppName}pkmnrpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnrpatch";                    ValueData: "MultiworldGG Pokemon Red Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnrpatch\DefaultIcon";        ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnrpatch\shell\open\command"; ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apblue";                                   ValueData: "{#MyAppName}pkmnbpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnbpatch";                    ValueData: "MultiworldGG Pokemon Blue Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnbpatch\DefaultIcon";        ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnbpatch\shell\open\command"; ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apbn3";                                    ValueData: "{#MyAppName}bn3bpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}bn3bpatch";                     ValueData: "MultiworldGG MegaMan Battle Network 3 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}bn3bpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}bn3bpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apemerald";                                 ValueData: "{#MyAppName}pkmnepatch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnepatch";                     ValueData: "MultiworldGG Pokemon Emerald Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnepatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}pkmnepatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmlss";                                 ValueData: "{#MyAppName}mlsspatch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mlsspatch";                     ValueData: "MultiworldGG Mario & Luigi Superstar Saga Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mlsspatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mlsspatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apcv64";                                 ValueData: "{#MyAppName}cv64patch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cv64patch";                     ValueData: "MultiworldGG Castlevania 64 Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cv64patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cv64patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apcvcotm";                                 ValueData: "{#MyAppName}cvcotmpatch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cvcotmpatch";                     ValueData: "MultiworldGG Castlevania Circle of the Moon Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cvcotmpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGBizHawkClient.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cvcotmpatch\shell\open\command";  ValueData: """{app}\MultiworldGGBizHawkClient.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apcvdos";                                 ValueData: "{#MyAppName}cvdospatch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cvdospatch";                     ValueData: "MultiworldGG Castlevania Dawn of Sorrow Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cvdospatch\DefaultIcon";         ValueData: "{app}\MultiworldGGBizHawkClient.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}cvdospatch\shell\open\command";  ValueData: """{app}\MultiworldGGBizHawkClient.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmm2";                                   ValueData: "{#MyAppName}mm2patch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm2patch";                     ValueData: "MultiworldGG Mega Man 2 Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm2patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm2patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmm3";                                   ValueData: "{#MyAppName}mm3patch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm3patch";                     ValueData: "MultiworldGG Mega Man 3 Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm3patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm3patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmmx3";                                   ValueData: "{#MyAppName}mmx3patch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mmx3patch";                     ValueData: "MultiworldGG Mega Man X3 Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mmx3patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mmx3patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apladx";                                   ValueData: "{#MyAppName}ladxpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ladxpatch";                     ValueData: "MultiworldGG Links Awakening DX Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ladxpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ladxpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apladxb";                                   ValueData: "{#MyAppName}ladxbpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ladxbpatch";                     ValueData: "MultiworldGG Links Awakening DX Beta Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ladxbpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ladxbpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".aptloz";                                   ValueData: "{#MyAppName}tlozpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}tlozpatch";                     ValueData: "MultiworldGG The Legend of Zelda Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}tlozpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGBizHawkClient.exe,0";                          ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}tlozpatch\shell\open\command";  ValueData: """{app}\MultiworldGGBizHawkClient.exe"" ""%1""";                     ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apadvn";                                   ValueData: "{#MyAppName}advnpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}advnpatch";                     ValueData: "MultiworldGG Adventure Patch";  Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}advnpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}advnpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";       ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apyi";                                   ValueData: "{#MyAppName}yipatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}yipatch";                     ValueData: "MultiworldGG Yoshi's Island Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}yipatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}yipatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apygo06";                                   ValueData: "{#MyAppName}ygo06patch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ygo06patch";                     ValueData: "MultiworldGG Yu-Gi-Oh 2006 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ygo06patch\DefaultIcon";         ValueData: "{app}\MultiworldGGBizHawkClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}ygo06patch\shell\open\command";  ValueData: """{app}\MultiworldGGBizHawkClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apalbw";                                   ValueData: "{#MyAppName}apalbwpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apalbwpatch";                     ValueData: "MultiworldGG A Link Between Worlds Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apalbwpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGLauncher.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apalbwpatch\shell\open\command";  ValueData: """{app}\MultiworldGGLauncher.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apbfbb";                                   ValueData: "{#MyAppName}apbfbbpatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apbfbbpatch";                     ValueData: "MultiworldGG Spongebob: BFBB Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apbfbbpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGLauncher.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apbfbbpatch\shell\open\command";  ValueData: """{app}\MultiworldGGLauncher.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apcivvi";                                   ValueData: "{#MyAppName}apcivvipatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apcivvipatch";                     ValueData: "MultiworldGG Civilization 6 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apcivvipatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apcivvipatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apcrystal";                                     ValueData: "{#MyAppName}apcrystalpatch";    Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apcrystalpatch";                     ValueData: "MultiworldGG Pkmn Crystal Patch"; Flags: uninsdeletekey;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apcrystalpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apcrystalpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apdkc";                                   ValueData: "{#MyAppName}dkcpatch";        Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkcpatch";                     ValueData: "MultiworldGG Donkey Kong Country Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkcpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkcpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apdkc2";                                   ValueData: "{#MyAppName}dkc2patch";        Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkc2patch";                     ValueData: "MultiworldGG Donkey Kong Country 2 Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkc2patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}dkc2patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apeb";                                   ValueData: "{#MyAppName}apebpatch";        Flags: uninsdeletevalue;         ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apebpatch";                     ValueData: "MultiworldGG Earthbound Patch"; Flags: uninsdeletekey;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apebpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apebpatch\shell\open\command";  ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apeos";                                     ValueData: "{#MyAppName}apeospatch";    Flags: uninsdeletevalue;           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apeospatch";                     ValueData: "MultiworldGG Pkmn MD Explorers of Sky Patch"; Flags: uninsdeletekey;  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apeospatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apeospatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apff4fe";                                   ValueData: "{#MyAppName}apff4fepatch";        Flags: uninsdeletevalue;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apff4fepatch";                     ValueData: "MultiworldGG Final Fantase IV: FE Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apff4fepatch\DefaultIcon";         ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apff4fepatch\shell\open\command";  ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apffvcd";                                     ValueData: "{#MyAppName}apffvcdpatch";        Flags: uninsdeletevalue;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apffvcdpatch";                     ValueData: "MultiworldGG Final Fantasy 5 CD Patch"; Flags: uninsdeletekey;        ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apffvcdpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apffvcdpatch\shell\open\command";  ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apfirered";                                     ValueData: "{#MyAppName}apfireredpatch";    Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apfireredpatch";                     ValueData: "MultiworldGG Pkmn Firered Patch"; Flags: uninsdeletekey;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apfireredpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apfireredpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apfm";                                     ValueData: "{#MyAppName}apfmpatch";    Flags: uninsdeletevalue;            ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apfmpatch";                     ValueData: "MultiworldGG Yu-Gi-Oh! Forbidden Memories Patch"; Flags: uninsdeletekey;  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apfmpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apfmpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apgstla";                                     ValueData: "{#MyAppName}apgstlapatch";    Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apgstlapatch";                     ValueData: "MultiworldGG Golden Sun TLA Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apgstlapatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apgstlapatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apk64cs";                                     ValueData: "{#MyAppName}apk64cspatch";    Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apk64cspatch";                     ValueData: "MultiworldGG Kirby 64 Patch"; Flags: uninsdeletekey;         ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apk64cspatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apk64cspatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apleafgreen";                                     ValueData: "{#MyAppName}apleafgreenpatch";    Flags: uninsdeletevalue;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apleafgreenpatch";                     ValueData: "MultiworldGG Pkmn Leafgreen Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apleafgreenpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apleafgreenpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".aplm";                                     ValueData: "{#MyAppName}aplmpatch";    Flags: uninsdeletevalue;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aplmpatch";                     ValueData: "MultiworldGG Luigi's Mansion Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aplmpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGLauncher.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aplmpatch\shell\open\command";  ValueData: """{app}\MultiworldGGLauncher.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmetfus";                                     ValueData: "{#MyAppName}apmetfuspatch";    Flags: uninsdeletevalue;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmetfuspatch";                     ValueData: "MultiworldGG Metroid Fusion Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmetfuspatch\DefaultIcon";         ValueData: "{app}\MultiworldGGBizHawkClient.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmetfuspatch\shell\open\command";  ValueData: """{app}\MultiworldGGBizHawkClient.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmk64";                                     ValueData: "{#MyAppName}apmk64patch";    Flags: uninsdeletevalue;        ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmk64patch";                     ValueData: "MultiworldGG Mario Kart 64 Patch"; Flags: uninsdeletekey;    ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmk64patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmk64patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apmmhd";                                     ValueData: "{#MyAppName}apmmhdpatch";        Flags: uninsdeletevalue;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmmhdpatch";                     ValueData: "MultiworldGG Madou Monogatari Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmmhdpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmmhdpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apmmhd";                                     ValueData: "{#MyAppName}apmmhdpatch";        Flags: uninsdeletevalue;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmmhdpatch";                     ValueData: "MultiworldGG Madou Monogatari Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmmhdpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmmhdpatch\shell\open\command";  ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apmzm";                                     ValueData: "{#MyAppName}apmzmpatch";    Flags: uninsdeletevalue;          ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmzmpatch";                     ValueData: "MultiworldGG Metroid Zero Mission Patch"; Flags: uninsdeletekey;  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmzmpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apmzmpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apooa";                                     ValueData: "{#MyAppName}apooapatch";    Flags: uninsdeletevalue;        ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apooapatch";                     ValueData: "MultiworldGG Oracle of Ages Patch"; Flags: uninsdeletekey;  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apooapatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                     ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apooapatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";            ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apoos";                                     ValueData: "{#MyAppName}apoospatch";    Flags: uninsdeletevalue;           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apoospatch";                     ValueData: "MultiworldGG Oracle of Seasons Patch"; Flags: uninsdeletekey;  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apoospatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apoospatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".appm64";                                     ValueData: "{#MyAppName}appm64patch";    Flags: uninsdeletevalue;          ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}appm64patch";                     ValueData: "MultiworldGG Paper Mario 64 Patch"; Flags: uninsdeletekey;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}appm64patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                        ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}appm64patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";               ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apsmmr";                                     ValueData: "{#MyAppName}apsmmrpatch";        Flags: uninsdeletevalue;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsmmrpatch";                     ValueData: "MultiworldGG SM Map Rando Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsmmrpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsmmrpatch\shell\open\command";  ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apsms";                                     ValueData: "{#MyAppName}apsmspatch";    Flags: uninsdeletevalue;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsmspatch";                     ValueData: "MultiworldGG Super Mario Sunshine Patch"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsmspatch\DefaultIcon";         ValueData: "{app}\MultiworldGGLauncher.exe,0";                      ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsmspatch\shell\open\command";  ValueData: """{app}\MultiworldGGLauncher.exe"" ""%1""";             ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apsotn";                                   ValueData: "{#MyAppName}apsotnpatch";      Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsotnpatch";                     ValueData: "MultiworldGG SotN Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsotnpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";               ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apsotnpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";      ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".aptatk";                                     ValueData: "{#MyAppName}aptatkpatch";        Flags: uninsdeletevalue;     ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aptatkpatch";                     ValueData: "MultiworldGG Tetris Attack Patch"; Flags: uninsdeletekey;        ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aptatkpatch\DefaultIcon";         ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aptatkpatch\shell\open\command";  ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apttyd";                                     ValueData: "{#MyAppName}apttydpatch";    Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apttydpatch";                     ValueData: "MultiworldGG TTYD Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apttydpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                    ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apttydpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";           ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apwaffle";                                        ValueData: "{#MyAppName}smwwafflespatch";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smwwafflespatch";                      ValueData: "MultiworldGG SMW Waffles Patch";     Flags: uninsdeletekey; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smwwafflespatch\DefaultIcon";          ValueData: "{app}\MultiworldGGSNIClient.exe,0";                           ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}smwwafflespatch\shell\open\command";   ValueData: """{app}\MultiworldGGSNIClient.exe"" ""%1""";                  ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apwl";                                     ValueData: "{#MyAppName}apwlpatch";    Flags: uninsdeletevalue;         ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apwlpatch";                     ValueData: "MultiworldGG Wario Land Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apwlpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                     ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apwlpatch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";            ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apwl4";                                     ValueData: "{#MyAppName}apwl4patch";    Flags: uninsdeletevalue;          ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apwl4patch";                     ValueData: "MultiworldGG Wario Land 4 Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apwl4patch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                       ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apwl4patch\shell\open\command";  ValueData: """{app}\MultiWorldGG.exe"" ""%1""";              ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apygoddm";                                     ValueData: "{#MyAppName}apygoddmpatch";    Flags: uninsdeletevalue;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apygoddmpatch";                     ValueData: "MultiworldGG Yu-Gi-Oh! Dungeon Dice Monsters Patch"; Flags: uninsdeletekey;  ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apygoddmpatch\DefaultIcon";         ValueData: "{app}\MultiWorldGG.exe,0";                   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apygoddmpatch\shell\open\command";  ValueData: """{app}\MultiworldGG.exe"" ""%1""";          ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".apz2";                                     ValueData: "{#MyAppName}apz2patch";    Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apz2patch";                     ValueData: "MultiworldGG Zelda II Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apz2patch\DefaultIcon";         ValueData: "{app}\MultiworldGG.exe,0";                   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}apz2patch\shell\open\command";  ValueData: """{app}\MultiworldGG.exe"" ""%1""";          ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".aptmc";                                     ValueData: "{#MyAppName}aptmcpatch";    Flags: uninsdeletevalue;       ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aptmcpatch";                     ValueData: "MultiworldGG The Minish Cap Patch"; Flags: uninsdeletekey;      ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aptmcpatch\DefaultIcon";         ValueData: "{app}\MultiworldGG.exe,0";                   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}aptmcpatch\shell\open\command";  ValueData: """{app}\MultiworldGG.exe"" ""%1""";          ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".multiworldgg";                              ValueData: "{#MyAppName}multidata";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}multidata";                     ValueData: "MultiworldGG Server Data";      Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}multidata\DefaultIcon";         ValueData: "{app}\MultiworldGGServer.exe,0";                         ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}multidata\shell\open\command";  ValueData: """{app}\MultiworldGGServer.exe"" ""%1""";                ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apmm3";                                   ValueData: "{#MyAppName}mm3patch";                               Flags: uninsdeletevalue; ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm3patch";                     ValueData: "Archipelago Mega Man 3 Patch";                    Flags: uninsdeletekey;   ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm3patch\DefaultIcon";         ValueData: "{app}\ArchipelagoBizHawkClient.exe,0";                                          ValueType: string; ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}mm3patch\shell\open\command";  ValueData: """{app}\ArchipelagoBizHawkClient.exe"" ""%1""";                                 ValueType: string; ValueName: "";

Root: HKCR; Subkey: ".archipelago";                              ValueData: "{#MyAppName}multidata";        Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}multidata";                     ValueData: "MultiworldGG Server Data";      Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}multidata\DefaultIcon";         ValueData: "{app}\MultiworldGGServer.exe,0";                         ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}multidata\shell\open\command";  ValueData: """{app}\MultiworldGGServer.exe"" ""%1""";                ValueType: string;  ValueName: "";

Root: HKCR; Subkey: ".apworld";                                 ValueData: "{#MyAppName}worlddata";  Flags: uninsdeletevalue; ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}worlddata";                    ValueData: "MultiworldGG World Data"; Flags: uninsdeletekey;   ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}worlddata\DefaultIcon";        ValueData: "{app}\MultiworldGG.exe,0";                 ValueType: string;  ValueName: "";
Root: HKCR; Subkey: "{#MyAppName}worlddata\shell\open\command"; ValueData: """{app}\MultiworldGG.exe"" ""%1""";        ValueType: string;  ValueName: "";

Root: HKCR; Subkey: "mwgg"; ValueType: "string"; ValueData: "MultiworldGG Protocol"; Flags: uninsdeletekey;
Root: HKCR; Subkey: "mwgg"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: "";
Root: HKCR; Subkey: "mwgg\DefaultIcon"; ValueType: "string"; ValueData: "{app}\MultiWorldGG.exe,0";
Root: HKCR; Subkey: "mwgg\shell\open\command"; ValueType: "string"; ValueData: """{app}\MultiworldGG.exe"" ""%1""";

Root: HKCR; Subkey: "archipelago"; ValueType: "string"; ValueData: "MultiworldGG Protocol"; Flags: uninsdeletekey;
Root: HKCR; Subkey: "archipelago"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: "";
Root: HKCR; Subkey: "archipelago\DefaultIcon"; ValueType: "string"; ValueData: "{app}\MultiWorldGG.exe,0";
Root: HKCR; Subkey: "archipelago\shell\open\command"; ValueType: "string"; ValueData: """{app}\MultiworldGG.exe"" ""%1""";

Root: HKCR; Subkey: "multiworldgg"; ValueType: "string"; ValueData: "MultiworldGG Protocol"; Flags: uninsdeletekey;
Root: HKCR; Subkey: "multiworldgg"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: "";
Root: HKCR; Subkey: "multiworldgg\DefaultIcon"; ValueType: "string"; ValueData: "{app}\MultiWorldGG.exe,0";
Root: HKCR; Subkey: "multiworldgg\shell\open\command"; ValueType: "string"; ValueData: """{app}\MultiworldGG.exe"" ""%1""";


[Code]
var
  WorldPage: TInputOptionWizardPage;
  ComponentsLabel: TNewStaticText;

procedure InitializeWizard;
begin
  // Add custom disclaimer to Components page
  ComponentsLabel := TNewStaticText.Create(WizardForm);
  ComponentsLabel.Parent := WizardForm.SelectComponentsPage;
  ComponentsLabel.Top := WizardForm.SelectComponentsLabel.Top;
  ComponentsLabel.Left := WizardForm.SelectComponentsLabel.Left;
  ComponentsLabel.Width := WizardForm.SelectComponentsLabel.Width + ScaleX(70);
  ComponentsLabel.Height := WizardForm.SelectComponentsLabel.Height;
  ComponentsLabel.AutoSize := False;
  ComponentsLabel.WordWrap := True;
  ComponentsLabel.Font.Style := [fsBold];
  ComponentsLabel.Font.Color := clRed;
  ComponentsLabel.Caption := 'IMPORTANT: These modules are for playing MultiWorlds with your own legally obtained copies of the games listed. They WILL NOT install the game. Free games shown in BOLD';

  WorldPage := CreateInputOptionPage(wpSelectTasks,
    'Select Age Rating for Games List', 
    'Choose the age rating for the games list to use initially. The options are: 12+, 16+, and NR (Not Rated). Not rated games are suitable for 18 or simply games that are unknown. Note that adult only games are not found in these indexes.',
    'Select one of the following age ratings for the initial games list. This setting can be changed later.', 
    True, False);

  WorldPage.Add('PEGI 12');
  WorldPage.Add('PEGI 16');
  WorldPage.Add('NR');

  // Set default to sixteen (index 1)
  WorldPage.SelectedValueIndex := 1;
end;

function GetSelectedWorld(Param: String): String;
var
  WorldList: String;
begin
  // Start with the required IGDB selection
  if WorldPage.SelectedValueIndex = 0 then
    WorldList := 'mwgg_igdb_twelve'
  else if WorldPage.SelectedValueIndex = 1 then
    WorldList := 'mwgg_igdb_sixteen'
  else
    WorldList := 'mwgg_igdb_nr';
  
  // Add selected optional world components
  // BEGIN AUTOGEN: dispatch (regenerated by tools/regen_inno_components.py from mwgg_igdb_sixteen)
  if WizardIsComponentSelected('worlds\against_the_storm') then WorldList := WorldList + ' worlds.against_the_storm';
  if WizardIsComponentSelected('worlds\ahit') then WorldList := WorldList + ' worlds.ahit';
  if WizardIsComponentSelected('worlds\albw') then WorldList := WorldList + ' worlds.albw';
  if WizardIsComponentSelected('worlds\alttp') then WorldList := WorldList + ' worlds.alttp';
  if WizardIsComponentSelected('worlds\animal_well') then WorldList := WorldList + ' worlds.animal_well';
  if WizardIsComponentSelected('worlds\apeescape') then WorldList := WorldList + ' worlds.apeescape';
  if WizardIsComponentSelected('worlds\apgo') then WorldList := WorldList + ' worlds.apgo';
  if WizardIsComponentSelected('worlds\apquest') then WorldList := WorldList + ' worlds.apquest';
  if WizardIsComponentSelected('worlds\apsudoku') then WorldList := WorldList + ' worlds.apsudoku';
  if WizardIsComponentSelected('worlds\archipidle') then WorldList := WorldList + ' worlds.archipidle';
  if WizardIsComponentSelected('worlds\balatro') then WorldList := WorldList + ' worlds.balatro';
  if WizardIsComponentSelected('worlds\banjo_tooie') then WorldList := WorldList + ' worlds.banjo_tooie';
  if WizardIsComponentSelected('worlds\bfbb') then WorldList := WorldList + ' worlds.bfbb';
  if WizardIsComponentSelected('worlds\blasphemous') then WorldList := WorldList + ' worlds.blasphemous';
  if WizardIsComponentSelected('worlds\bomb_rush_cyberfunk') then WorldList := WorldList + ' worlds.bomb_rush_cyberfunk';
  if WizardIsComponentSelected('worlds\brotato') then WorldList := WorldList + ' worlds.brotato';
  if WizardIsComponentSelected('worlds\cat_quest') then WorldList := WorldList + ' worlds.cat_quest';
  if WizardIsComponentSelected('worlds\cccharles') then WorldList := WorldList + ' worlds.cccharles';
  if WizardIsComponentSelected('worlds\celeste') then WorldList := WorldList + ' worlds.celeste';
  if WizardIsComponentSelected('worlds\celeste_open_world') then WorldList := WorldList + ' worlds.celeste_open_world';
  if WizardIsComponentSelected('worlds\chainedechoes') then WorldList := WorldList + ' worlds.chainedechoes';
  if WizardIsComponentSelected('worlds\chatipelago') then WorldList := WorldList + ' worlds.chatipelago';
  if WizardIsComponentSelected('worlds\checksfinder') then WorldList := WorldList + ' worlds.checksfinder';
  if WizardIsComponentSelected('worlds\civ_6') then WorldList := WorldList + ' worlds.civ_6';
  if WizardIsComponentSelected('worlds\clique') then WorldList := WorldList + ' worlds.clique';
  if WizardIsComponentSelected('worlds\crosscode') then WorldList := WorldList + ' worlds.crosscode';
  if WizardIsComponentSelected('worlds\crystal_project') then WorldList := WorldList + ' worlds.crystal_project';
  if WizardIsComponentSelected('worlds\ctjot') then WorldList := WorldList + ' worlds.ctjot';
  if WizardIsComponentSelected('worlds\cuphead') then WorldList := WorldList + ' worlds.cuphead';
  if WizardIsComponentSelected('worlds\cv64') then WorldList := WorldList + ' worlds.cv64';
  if WizardIsComponentSelected('worlds\cv_dos') then WorldList := WorldList + ' worlds.cv_dos';
  if WizardIsComponentSelected('worlds\cvcotm') then WorldList := WorldList + ' worlds.cvcotm';
  if WizardIsComponentSelected('worlds\dark_souls_2') then WorldList := WorldList + ' worlds.dark_souls_2';
  if WizardIsComponentSelected('worlds\dark_souls_3') then WorldList := WorldList + ' worlds.dark_souls_3';
  if WizardIsComponentSelected('worlds\diddy_kong_racing') then WorldList := WorldList + ' worlds.diddy_kong_racing';
  if WizardIsComponentSelected('worlds\dk64') then WorldList := WorldList + ' worlds.dk64';
  if WizardIsComponentSelected('worlds\dkc') then WorldList := WorldList + ' worlds.dkc';
  if WizardIsComponentSelected('worlds\dkc2') then WorldList := WorldList + ' worlds.dkc2';
  if WizardIsComponentSelected('worlds\dontstarvetogether') then WorldList := WorldList + ' worlds.dontstarvetogether';
  if WizardIsComponentSelected('worlds\doom_1993') then WorldList := WorldList + ' worlds.doom_1993';
  if WizardIsComponentSelected('worlds\doom_ii') then WorldList := WorldList + ' worlds.doom_ii';
  if WizardIsComponentSelected('worlds\doronko_wanko') then WorldList := WorldList + ' worlds.doronko_wanko';
  if WizardIsComponentSelected('worlds\dredge') then WorldList := WorldList + ' worlds.dredge';
  if WizardIsComponentSelected('worlds\dsr') then WorldList := WorldList + ' worlds.dsr';
  if WizardIsComponentSelected('worlds\dw1') then WorldList := WorldList + ' worlds.dw1';
  if WizardIsComponentSelected('worlds\earthbound') then WorldList := WorldList + ' worlds.earthbound';
  if WizardIsComponentSelected('worlds\enderlilies') then WorldList := WorldList + ' worlds.enderlilies';
  if WizardIsComponentSelected('worlds\factorio') then WorldList := WorldList + ' worlds.factorio';
  if WizardIsComponentSelected('worlds\factorio_saws') then WorldList := WorldList + ' worlds.factorio_saws';
  if WizardIsComponentSelected('worlds\faxanadu') then WorldList := WorldList + ' worlds.faxanadu';
  if WizardIsComponentSelected('worlds\ff1') then WorldList := WorldList + ' worlds.ff1';
  if WizardIsComponentSelected('worlds\ff4fe') then WorldList := WorldList + ' worlds.ff4fe';
  if WizardIsComponentSelected('worlds\ffmq') then WorldList := WorldList + ' worlds.ffmq';
  if WizardIsComponentSelected('worlds\ffta') then WorldList := WorldList + ' worlds.ffta';
  if WizardIsComponentSelected('worlds\fm') then WorldList := WorldList + ' worlds.fm';
  if WizardIsComponentSelected('worlds\getting_over_it') then WorldList := WorldList + ' worlds.getting_over_it';
  if WizardIsComponentSelected('worlds\gstla') then WorldList := WorldList + ' worlds.gstla';
  if WizardIsComponentSelected('worlds\hades') then WorldList := WorldList + ' worlds.hades';
  if WizardIsComponentSelected('worlds\hcniko') then WorldList := WorldList + ' worlds.hcniko';
  if WizardIsComponentSelected('worlds\hk') then WorldList := WorldList + ' worlds.hk';
  if WizardIsComponentSelected('worlds\into_the_breach') then WorldList := WorldList + ' worlds.into_the_breach';
  if WizardIsComponentSelected('worlds\jakanddaxter') then WorldList := WorldList + ' worlds.jakanddaxter';
  if WizardIsComponentSelected('worlds\jigsaw') then WorldList := WorldList + ' worlds.jigsaw';
  if WizardIsComponentSelected('worlds\k64') then WorldList := WorldList + ' worlds.k64';
  if WizardIsComponentSelected('worlds\kdl3') then WorldList := WorldList + ' worlds.kdl3';
  if WizardIsComponentSelected('worlds\kh1') then WorldList := WorldList + ' worlds.kh1';
  if WizardIsComponentSelected('worlds\kh2') then WorldList := WorldList + ' worlds.kh2';
  if WizardIsComponentSelected('worlds\landstalker') then WorldList := WorldList + ' worlds.landstalker';
  if WizardIsComponentSelected('worlds\lego_star_wars_tcs') then WorldList := WorldList + ' worlds.lego_star_wars_tcs';
  if WizardIsComponentSelected('worlds\lufia2ac') then WorldList := WorldList + ' worlds.lufia2ac';
  if WizardIsComponentSelected('worlds\luigismansion') then WorldList := WorldList + ' worlds.luigismansion';
  if WizardIsComponentSelected('worlds\mario_kart_double_dash') then WorldList := WorldList + ' worlds.mario_kart_double_dash';
  if WizardIsComponentSelected('worlds\marioland2') then WorldList := WorldList + ' worlds.marioland2';
  if WizardIsComponentSelected('worlds\megamix') then WorldList := WorldList + ' worlds.megamix';
  if WizardIsComponentSelected('worlds\messenger') then WorldList := WorldList + ' worlds.messenger';
  if WizardIsComponentSelected('worlds\metroidfusion') then WorldList := WorldList + ' worlds.metroidfusion';
  if WizardIsComponentSelected('worlds\metroidprime') then WorldList := WorldList + ' worlds.metroidprime';
  if WizardIsComponentSelected('worlds\minecraft') then WorldList := WorldList + ' worlds.minecraft';
  if WizardIsComponentSelected('worlds\mk64') then WorldList := WorldList + ' worlds.mk64';
  if WizardIsComponentSelected('worlds\mlss') then WorldList := WorldList + ' worlds.mlss';
  if WizardIsComponentSelected('worlds\mm2') then WorldList := WorldList + ' worlds.mm2';
  if WizardIsComponentSelected('worlds\mm3') then WorldList := WorldList + ' worlds.mm3';
  if WizardIsComponentSelected('worlds\mm_recomp') then WorldList := WorldList + ' worlds.mm_recomp';
  if WizardIsComponentSelected('worlds\mmbn3') then WorldList := WorldList + ' worlds.mmbn3';
  if WizardIsComponentSelected('worlds\mmx3') then WorldList := WorldList + ' worlds.mmx3';
  if WizardIsComponentSelected('worlds\momodoramoonlitfarewell') then WorldList := WorldList + ' worlds.momodoramoonlitfarewell';
  if WizardIsComponentSelected('worlds\monster_sanctuary') then WorldList := WorldList + ' worlds.monster_sanctuary';
  if WizardIsComponentSelected('worlds\musedash') then WorldList := WorldList + ' worlds.musedash';
  if WizardIsComponentSelected('worlds\mzm') then WorldList := WorldList + ' worlds.mzm';
  if WizardIsComponentSelected('worlds\nine_sols') then WorldList := WorldList + ' worlds.nine_sols';
  if WizardIsComponentSelected('worlds\oot') then WorldList := WorldList + ' worlds.oot';
  if WizardIsComponentSelected('worlds\ori_wotw') then WorldList := WorldList + ' worlds.ori_wotw';
  if WizardIsComponentSelected('worlds\oribf') then WorldList := WorldList + ' worlds.oribf';
  if WizardIsComponentSelected('worlds\osrs') then WorldList := WorldList + ' worlds.osrs';
  if WizardIsComponentSelected('worlds\outer_wilds') then WorldList := WorldList + ' worlds.outer_wilds';
  if WizardIsComponentSelected('worlds\overcooked2') then WorldList := WorldList + ' worlds.overcooked2';
  if WizardIsComponentSelected('worlds\paint') then WorldList := WorldList + ' worlds.paint';
  if WizardIsComponentSelected('worlds\papermario') then WorldList := WorldList + ' worlds.papermario';
  if WizardIsComponentSelected('worlds\phoa') then WorldList := WorldList + ' worlds.phoa';
  if WizardIsComponentSelected('worlds\placidplasticducksim') then WorldList := WorldList + ' worlds.placidplasticducksim';
  if WizardIsComponentSelected('worlds\pmd_eos') then WorldList := WorldList + ' worlds.pmd_eos';
  if WizardIsComponentSelected('worlds\pokemon_crystal') then WorldList := WorldList + ' worlds.pokemon_crystal';
  if WizardIsComponentSelected('worlds\pokemon_emerald') then WorldList := WorldList + ' worlds.pokemon_emerald';
  if WizardIsComponentSelected('worlds\pokemon_frlg') then WorldList := WorldList + ' worlds.pokemon_frlg';
  if WizardIsComponentSelected('worlds\pokemon_rb') then WorldList := WorldList + ' worlds.pokemon_rb';
  if WizardIsComponentSelected('worlds\powerwashsimulator') then WorldList := WorldList + ' worlds.powerwashsimulator';
  if WizardIsComponentSelected('worlds\quake') then WorldList := WorldList + ' worlds.quake';
  if WizardIsComponentSelected('worlds\rabi_ribi') then WorldList := WorldList + ' worlds.rabi_ribi';
  if WizardIsComponentSelected('worlds\rac2') then WorldList := WorldList + ' worlds.rac2';
  if WizardIsComponentSelected('worlds\raft') then WorldList := WorldList + ' worlds.raft';
  if WizardIsComponentSelected('worlds\refunct') then WorldList := WorldList + ' worlds.refunct';
  if WizardIsComponentSelected('worlds\rimworld') then WorldList := WorldList + ' worlds.rimworld';
  if WizardIsComponentSelected('worlds\rogue_legacy') then WorldList := WorldList + ' worlds.rogue_legacy';
  if WizardIsComponentSelected('worlds\ror1') then WorldList := WorldList + ' worlds.ror1';
  if WizardIsComponentSelected('worlds\ror2') then WorldList := WorldList + ' worlds.ror2';
  if WizardIsComponentSelected('worlds\rotn') then WorldList := WorldList + ' worlds.rotn';
  if WizardIsComponentSelected('worlds\sa2b') then WorldList := WorldList + ' worlds.sa2b';
  if WizardIsComponentSelected('worlds\sadx') then WorldList := WorldList + ' worlds.sadx';
  if WizardIsComponentSelected('worlds\satisfactory') then WorldList := WorldList + ' worlds.satisfactory';
  if WizardIsComponentSelected('worlds\sc2') then WorldList := WorldList + ' worlds.sc2';
  if WizardIsComponentSelected('worlds\seaofthieves') then WorldList := WorldList + ' worlds.seaofthieves';
  if WizardIsComponentSelected('worlds\shivers') then WorldList := WorldList + ' worlds.shivers';
  if WizardIsComponentSelected('worlds\shorthike') then WorldList := WorldList + ' worlds.shorthike';
  if WizardIsComponentSelected('worlds\simpsonshitnrun') then WorldList := WorldList + ' worlds.simpsonshitnrun';
  if WizardIsComponentSelected('worlds\sims4') then WorldList := WorldList + ' worlds.sims4';
  if WizardIsComponentSelected('worlds\sly1') then WorldList := WorldList + ' worlds.sly1';
  if WizardIsComponentSelected('worlds\sm') then WorldList := WorldList + ' worlds.sm';
  if WizardIsComponentSelected('worlds\sm64ex') then WorldList := WorldList + ' worlds.sm64ex';
  if WizardIsComponentSelected('worlds\sm64hacks') then WorldList := WorldList + ' worlds.sm64hacks';
  if WizardIsComponentSelected('worlds\sm_map_rando') then WorldList := WorldList + ' worlds.sm_map_rando';
  if WizardIsComponentSelected('worlds\smo') then WorldList := WorldList + ' worlds.smo';
  if WizardIsComponentSelected('worlds\sms') then WorldList := WorldList + ' worlds.sms';
  if WizardIsComponentSelected('worlds\smw') then WorldList := WorldList + ' worlds.smw';
  if WizardIsComponentSelected('worlds\soe') then WorldList := WorldList + ' worlds.soe';
  if WizardIsComponentSelected('worlds\sonic_heroes') then WorldList := WorldList + ' worlds.sonic_heroes';
  if WizardIsComponentSelected('worlds\sotn') then WorldList := WorldList + ' worlds.sotn';
  if WizardIsComponentSelected('worlds\spyro3') then WorldList := WorldList + ' worlds.spyro3';
  if WizardIsComponentSelected('worlds\ss') then WorldList := WorldList + ' worlds.ss';
  if WizardIsComponentSelected('worlds\star_fox_64') then WorldList := WorldList + ' worlds.star_fox_64';
  if WizardIsComponentSelected('worlds\stardew_valley') then WorldList := WorldList + ' worlds.stardew_valley';
  if WizardIsComponentSelected('worlds\subnautica') then WorldList := WorldList + ' worlds.subnautica';
  if WizardIsComponentSelected('worlds\swr') then WorldList := WorldList + ' worlds.swr';
  if WizardIsComponentSelected('worlds\tboir') then WorldList := WorldList + ' worlds.tboir';
  if WizardIsComponentSelected('worlds\terraria') then WorldList := WorldList + ' worlds.terraria';
  if WizardIsComponentSelected('worlds\tetrisattack') then WorldList := WorldList + ' worlds.tetrisattack';
  if WizardIsComponentSelected('worlds\timespinner') then WorldList := WorldList + ' worlds.timespinner';
  if WizardIsComponentSelected('worlds\tloz') then WorldList := WorldList + ' worlds.tloz';
  if WizardIsComponentSelected('worlds\tloz_ooa') then WorldList := WorldList + ' worlds.tloz_ooa';
  if WizardIsComponentSelected('worlds\tloz_oos') then WorldList := WorldList + ' worlds.tloz_oos';
  if WizardIsComponentSelected('worlds\tloz_ph') then WorldList := WorldList + ' worlds.tloz_ph';
  if WizardIsComponentSelected('worlds\tmc') then WorldList := WorldList + ' worlds.tmc';
  if WizardIsComponentSelected('worlds\toontown') then WorldList := WorldList + ' worlds.toontown';
  if WizardIsComponentSelected('worlds\tp') then WorldList := WorldList + ' worlds.tp';
  if WizardIsComponentSelected('worlds\trackmania') then WorldList := WorldList + ' worlds.trackmania';
  if WizardIsComponentSelected('worlds\tunic') then WorldList := WorldList + ' worlds.tunic';
  if WizardIsComponentSelected('worlds\tww') then WorldList := WorldList + ' worlds.tww';
  if WizardIsComponentSelected('worlds\tyrian') then WorldList := WorldList + ' worlds.tyrian';
  if WizardIsComponentSelected('worlds\ufo50') then WorldList := WorldList + ' worlds.ufo50';
  if WizardIsComponentSelected('worlds\undertale') then WorldList := WorldList + ' worlds.undertale';
  if WizardIsComponentSelected('worlds\v6') then WorldList := WorldList + ' worlds.v6';
  if WizardIsComponentSelected('worlds\waffles') then WorldList := WorldList + ' worlds.waffles';
  if WizardIsComponentSelected('worlds\wargroove') then WorldList := WorldList + ' worlds.wargroove';
  if WizardIsComponentSelected('worlds\wargroove2') then WorldList := WorldList + ' worlds.wargroove2';
  if WizardIsComponentSelected('worlds\witness') then WorldList := WorldList + ' worlds.witness';
  if WizardIsComponentSelected('worlds\wl') then WorldList := WorldList + ' worlds.wl';
  if WizardIsComponentSelected('worlds\wl4') then WorldList := WorldList + ' worlds.wl4';
  if WizardIsComponentSelected('worlds\wordipelago') then WorldList := WorldList + ' worlds.wordipelago';
  if WizardIsComponentSelected('worlds\xenobladex') then WorldList := WorldList + ' worlds.xenobladex';
  if WizardIsComponentSelected('worlds\yachtdice') then WorldList := WorldList + ' worlds.yachtdice';
  if WizardIsComponentSelected('worlds\yoshisisland') then WorldList := WorldList + ' worlds.yoshisisland';
  if WizardIsComponentSelected('worlds\yugioh06') then WorldList := WorldList + ' worlds.yugioh06';
  if WizardIsComponentSelected('worlds\yugiohddm') then WorldList := WorldList + ' worlds.yugiohddm';
  if WizardIsComponentSelected('worlds\zelda2') then WorldList := WorldList + ' worlds.zelda2';
  if WizardIsComponentSelected('worlds\zork_grand_inquisitor') then WorldList := WorldList + ' worlds.zork_grand_inquisitor';
  // END AUTOGEN: dispatch

  Result := WorldList;
end;

function ShouldShowDeleteLibTask: Boolean;
begin
  Result := DirExists(ExpandConstant('{app}\lib'));
end;

function IsUvInstalled: Boolean;
var
  ResultCode: Integer;
begin
  Result := False;
  // `where uv` exits 0 if uv.exe is on PATH (or on a known winget shim path).
  if Exec(ExpandConstant('{cmd}'), '/c where uv', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0) then
  begin
    Log('uv found on PATH');
    Result := True;
  end
  else
    Log('uv not found on PATH; will install');
end;

function IsWingetAvailable: Boolean;
var
  ResultCode: Integer;
begin
  Result := False;
  if Exec(ExpandConstant('{cmd}'), '/c where winget', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0) then
  begin
    Log('winget available');
    Result := True;
  end
  else
    Log('winget not available; will fall back to astral PowerShell installer');
end;

function IsUvNeededViaWinget: Boolean;
begin
  Result := (not IsUvInstalled) and IsWingetAvailable;
end;

function IsUvNeededViaPwsh: Boolean;
begin
  Result := (not IsUvInstalled) and (not IsWingetAvailable);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    if WizardIsTaskSelected('deletelib') then
      DelTree(ExpandConstant('{app}\lib'), True, True, True);
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  InClientList: TStringList;
  i: Integer;
begin
  if CurPageID = wpSelectComponents then
  begin
    // Bold the description of any in-client world. The descriptions list is
    // injected at compile time by the regenerator; matching is by description
    // text since TNewCheckListBox stores the visible caption, not the
    // component name.
    InClientList := TStringList.Create;
    try
      InClientList.CommaText := '{#InClientDescriptions}';
      for i := 0 to WizardForm.ComponentsList.Items.Count - 1 do
      begin
        if InClientList.IndexOf(WizardForm.ComponentsList.Items[i]) >= 0 then
          WizardForm.ComponentsList.ItemFontStyle[i] := [fsBold];
      end;
    finally
      InClientList.Free;
    end;
  end;
end;
