[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "jigsaw"
dynamic = ["version"]
description = "Jigsaw"
authors = [
    {name = "spinerak"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"jigsaw.WorldClass" = "jigsaw.Register:WORLD_CLASS"
"jigsaw.WebWorldClass" = "jigsaw.Register:WEB_WORLD_CLASS"
"jigsaw.Client" = "jigsaw.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["jigsaw*", "jigsaw"]
exclude = ["jigsaw/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
