[project]
name = "noita"
version = "1.0.0"
description = "Noita is a magical action roguelite set in a world where every pixel is physically simulated. Fight, explore, melt, burn, freeze, and evaporate your way through the procedurally generated world using wands you've created yourself."
authors = [
    {name = "ScipioWright & heinermann"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"noita.WorldClass" = "noita.Register:WORLD_CLASS"
"noita.WebWorldClass" = "noita.Register:WEB_WORLD_CLASS"
"noita.Client" = "noita.Register:CLIENT_FUNCTION"
