[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "noita"
dynamic = ["version"]
description = "Noita"
authors = [
    {name = "ScipioWright & heinermann"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"noita.WorldClass" = "noita.Register:WORLD_CLASS"
"noita.WebWorldClass" = "noita.Register:WEB_WORLD_CLASS"
"noita.Client" = "noita.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "noita.Register:VERSION"}
