[project]
name = "rogue_legacy"
version = "1.0.0"
description = "Rogue Legacy is a genealogical rogue-"LITE" where anyone can be a hero. Each time you die, your child will succeed you. Every child is unique. One child might be colorblind, another might have vertigo-- they could even be a dwarf. But that's OK, because no one is perfect, and you don't have to be to succeed."
authors = [
    {name = "Phar"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"rogue_legacy.WorldClass" = "rogue_legacy.Register:WORLD_CLASS"
"rogue_legacy.WebWorldClass" = "rogue_legacy.Register:WEB_WORLD_CLASS"
"rogue_legacy.Client" = "rogue_legacy.Register:CLIENT_FUNCTION"
