[project]
name = "dungeon_clawler"
version = "1.0.0"
description = "Dungeon Clawler mixes deck building with a dash of rogue-like mechanics and most importantly: a claw machine."
authors = [
    {name = "Kaito Kid"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dungeon_clawler.WorldClass" = "dungeon_clawler.Register:WORLD_CLASS"
"dungeon_clawler.WebWorldClass" = "dungeon_clawler.Register:WEB_WORLD_CLASS"
"dungeon_clawler.Client" = "dungeon_clawler.Register:CLIENT_FUNCTION"
