[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "minecraft"
dynamic = ["version"]
description = "Minecraft"
authors = [
    {name = "KonoTyran & espeon"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "requests >= 2.28.1  # used by client",
]

[project.entry-points."mwgg.plugins"]
"minecraft.WorldClass" = "minecraft.Register:WORLD_CLASS"
"minecraft.WebWorldClass" = "minecraft.Register:WEB_WORLD_CLASS"
"minecraft.Client" = "minecraft.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["minecraft*", "minecraft"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "minecraft.Constants.VERSION"}
