[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tww"
dynamic = ["version"]
description = "Legend has it that whenever evil has appeared, a hero named Link has arisen to defeat it. The legend continues on"
authors = [
    {name = "tanjo3"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "dolphin-memory-engine>=1.3.0",
]

[project.entry-points."mwgg.plugins"]
"tww.WorldClass" = "tww.Register:WORLD_CLASS"
"tww.WebWorldClass" = "tww.Register:WEB_WORLD_CLASS"
"tww.Client" = "tww.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
