[project]
name = "tww"
version = "1.0.0"
description = "Legend has it that whenever evil has appeared, a hero named Link has arisen to defeat it. The legend continues on the surface of a vast and mysterious sea as Link sets sail in his most epic, awe-inspiring adventure yet. Aided by a magical conductor's baton called the Wind Waker, he will face unimaginable monsters, explore puzzling dungeons, and meet a cast of unforgettable characters as he searches for his kidnapped sister."
authors = [
    {name = "tanjo3"}
]
requires-python = ">=3.12"

dependencies = [
    "dolphin-memory-engine>=1.3.0",
]

[project.entry-points."mwgg.plugins"]
"tww.WorldClass" = "tww.Register:WORLD_CLASS"
"tww.WebWorldClass" = "tww.Register:WEB_WORLD_CLASS"
"tww.Client" = "tww.Register:CLIENT_FUNCTION"
