[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "heretic"
dynamic = ["version"]
description = "Heretic"
authors = [
    {name = "Daivuk & Kaito Sinclaire"}
]
license = "Zlib"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"heretic.WorldClass" = "heretic.Register:WORLD_CLASS"
"heretic.WebWorldClass" = "heretic.Register:WEB_WORLD_CLASS"
"heretic.Client" = "heretic.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["heretic*", "heretic"]
exclude = ["heretic/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
