[project]
name = "heretic"
version = "1.0.0"
description = "Heretic is a dark fantasy first-person shooter video game released in December 1994. It was developed by Raven Software."
authors = [
    {name = "Daivuk & Kaito Sinclaire"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"heretic.WorldClass" = "heretic.Register:WORLD_CLASS"
"heretic.WebWorldClass" = "heretic.Register:WEB_WORLD_CLASS"
"heretic.Client" = "heretic.Register:CLIENT_FUNCTION"
