[project]
name = "dw1"
version = "1.0.0"
description = "Digimon World is a game about raising digital monsters and recruiting allies to save the digital world."
authors = [
    {name = "ArsonAssassin"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dw1.WorldClass" = "dw1.Register:WORLD_CLASS"
"dw1.WebWorldClass" = "dw1.Register:WEB_WORLD_CLASS"
"dw1.Client" = "dw1.Register:CLIENT_FUNCTION"
