[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dw1"
dynamic = ["version"]
description = "MultiWorld: Digimon World"
authors = [
    {name = "ArsonAssassin"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dw1.WorldClass" = "dw1.Register:WORLD_CLASS"
"dw1.WebWorldClass" = "dw1.Register:WEB_WORLD_CLASS"
"dw1.Client" = "dw1.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["dw1*", "dw1"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "dw1.Constants.VERSION"}
