[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "swr"
dynamic = ["version"]
description = "Star Wars Episode I Racer"
authors = [
    {name = "Johnny Hamcobbler"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"swr.WorldClass" = "swr.Register:WORLD_CLASS"
"swr.WebWorldClass" = "swr.Register:WEB_WORLD_CLASS"
"swr.Client" = "swr.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["swr*", "swr"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "swr.Constants.VERSION"}
