[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "monster_sanctuary"
dynamic = ["version"]
description = "Monster Sanctuary"
authors = [
    {name = "Saagael"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"monster_sanctuary.WorldClass" = "monster_sanctuary.Register:WORLD_CLASS"
"monster_sanctuary.WebWorldClass" = "monster_sanctuary.Register:WEB_WORLD_CLASS"
"monster_sanctuary.Client" = "monster_sanctuary.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["monster_sanctuary*", "monster_sanctuary"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "monster_sanctuary.Constants.VERSION"}
