[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sm64hacks"
dynamic = ["version"]
description = "SM64 Romhack"
authors = [
    {name = "DNVIC"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sm64hacks.WorldClass" = "sm64hacks.Register:WORLD_CLASS"
"sm64hacks.WebWorldClass" = "sm64hacks.Register:WEB_WORLD_CLASS"
"sm64hacks.Client" = "sm64hacks.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "sm64hacks.Register:VERSION"}
