[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tracker"
dynamic = ["version"]
description = "Universal Tracker"
authors = [
    {name = "Unknown"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tracker.WorldClass" = "tracker.Register:WORLD_CLASS"
"tracker.Client" = "tracker.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
