[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tloz_oos"
dynamic = ["version"]
description = "The Legend of Zelda - Oracle of Seasons"
authors = [
    {name = "Dinopony"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tloz_oos.WorldClass" = "tloz_oos.Register:WORLD_CLASS"
"tloz_oos.WebWorldClass" = "tloz_oos.Register:WEB_WORLD_CLASS"
"tloz_oos.Client" = "tloz_oos.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "tloz_oos.Register:VERSION"}
