[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ror1"
dynamic = ["version"]
description = "Risk of Rain"
authors = [
    {name = "studkid"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ror1.WorldClass" = "ror1.Register:WORLD_CLASS"
"ror1.WebWorldClass" = "ror1.Register:WEB_WORLD_CLASS"
"ror1.Client" = "ror1.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
