[project]
name = "ror1"
version = "1.0.0"
description = "Risk of Rain is a 2013 roguelike platform game developed by Hopoo Games. Players control the survivor of a space freighter crash on a strange planet. They attempt to survive by killing monsters and collecting items that can boost their offensive and defensive abilities."
authors = [
    {name = "studkid"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ror1.WorldClass" = "ror1.Register:WORLD_CLASS"
"ror1.WebWorldClass" = "ror1.Register:WEB_WORLD_CLASS"
"ror1.Client" = "ror1.Register:CLIENT_FUNCTION"
