[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "momodoramoonlitfarewell"
dynamic = ["version"]
description = "Momodora Moonlit Farewell"
authors = [
    {name = "alditto"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"momodoramoonlitfarewell.WorldClass" = "momodoramoonlitfarewell.Register:WORLD_CLASS"
"momodoramoonlitfarewell.WebWorldClass" = "momodoramoonlitfarewell.Register:WEB_WORLD_CLASS"
"momodoramoonlitfarewell.Client" = "momodoramoonlitfarewell.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "momodoramoonlitfarewell.Register:VERSION"}
