[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "raft"
dynamic = ["version"]
description = "Raft"
authors = [
    {name = "SunnyBat"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"raft.WorldClass" = "raft.Register:WORLD_CLASS"
"raft.WebWorldClass" = "raft.Register:WEB_WORLD_CLASS"
"raft.Client" = "raft.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["raft*", "raft"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "raft.Constants.VERSION"}
