[project]
name = "raft"
version = "0.3.5"
description = "Raft is a flooded world exploration game. You're stranded on a small raft in the middle of the ocean, and you must survive on trash floating by you on the top of the water and around/on any islands that you come across."
authors = [
    {name = "SunnyBat"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"raft.WorldClass" = "raft.Register:WORLD_CLASS"
"raft.WebWorldClass" = "raft.Register:WEB_WORLD_CLASS"
"raft.Client" = "raft.Register:CLIENT_FUNCTION"
