[project]
name = "mario_kart_double_dash"
version = "1.0.0"
description = "The fourth entry in Mario Kart series, Double Dash shakes up the gameplay by introducing 2 drivers per vehicle."
authors = [
    {name = "aXu"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mario_kart_double_dash.WorldClass" = "mario_kart_double_dash.Register:WORLD_CLASS"
"mario_kart_double_dash.WebWorldClass" = "mario_kart_double_dash.Register:WEB_WORLD_CLASS"
"mario_kart_double_dash.Client" = "mario_kart_double_dash.Register:CLIENT_FUNCTION"
