[project]
name = "saving_princess"
version = "1.0.0"
description = "Explore a space station crawling with rogue machines and even rival bounty hunters with the same objective as you - but with far, far different intentions! Expand your arsenal as you collect upgrades to your trusty arm cannon and armor!"
authors = [
    {name = "LeonarthCG"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"saving_princess.WorldClass" = "saving_princess.Register:WORLD_CLASS"
"saving_princess.WebWorldClass" = "saving_princess.Register:WEB_WORLD_CLASS"
"saving_princess.Client" = "saving_princess.Register:CLIENT_FUNCTION"
