[project]
name = "ufo50"
version = "1.0.0"
description = "UFO 50 is a collection of 50 single and multiplayer games from the creators of Spelunky, Downwell, Air Land & Sea, Skorpulac, Catacomb Kids, and Madhouse. Jump in and explore a variety of genres, from platformers and shoot 'em ups to puzzle games and RPGs. Our goal is to combine a familiar 8-bit aesthetic with new ideas and modern game design sensibilities."
authors = [
    {name = "LeonarthCG & ScipioWright"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ufo50.WorldClass" = "ufo50.Register:WORLD_CLASS"
"ufo50.WebWorldClass" = "ufo50.Register:WEB_WORLD_CLASS"
"ufo50.Client" = "ufo50.Register:CLIENT_FUNCTION"
