[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "lethal_company"
dynamic = ["version"]
description = "Lethal Company"
authors = [
    {name = "T0r1nn"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"lethal_company.WorldClass" = "lethal_company.Register:WORLD_CLASS"
"lethal_company.WebWorldClass" = "lethal_company.Register:WEB_WORLD_CLASS"
"lethal_company.Client" = "lethal_company.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "lethal_company.Register:VERSION"}
