[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dk64"
dynamic = ["version"]
description = "Donkey Kong 64 is a 3D collectathon platforming game."
authors = [
    {name = "2dos, Killklli, & Ballaam"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dk64.WorldClass" = "dk64.Register:WORLD_CLASS"
"dk64.WebWorldClass" = "dk64.Register:WEB_WORLD_CLASS"
"dk64.Client" = "dk64.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["dk64*", "dk64"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "dk64.Constants.VERSION"}
