[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sms"
dynamic = ["version"]
description = "Super Mario Sunshine"
authors = [
    {name = "Joshark"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "dolphin_memory_engine >= 1.1.3",
]

[project.entry-points."mwgg.plugins"]
"sms.WorldClass" = "sms.Register:WORLD_CLASS"
"sms.WebWorldClass" = "sms.Register:WEB_WORLD_CLASS"
"sms.Client" = "sms.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["sms*", "sms"]
exclude = ["sms/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
