[project]
name = "sms"
version = "0.2.0"
description = "The second Super Mario game to feature 3D gameplay. Coupled with F.L.U.D.D. (a talking water tank that can be used as a jetpack), Mario must clean the graffiti off of Delfino Isle and return light to the sky."
authors = [
    {name = "Joshark"}
]
requires-python = ">=3.12"

dependencies = [
    "dolphin_memory_engine >= 1.1.3",
]

[project.entry-points."mwgg.plugins"]
"sms.WorldClass" = "sms.Register:WORLD_CLASS"
"sms.WebWorldClass" = "sms.Register:WEB_WORLD_CLASS"
"sms.Client" = "sms.Register:CLIENT_FUNCTION"
