[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "osu"
dynamic = ["version"]
description = "osu! is a free to play rhythm game featuring 4 modes, an online ranking system/statistics,"
authors = [
    {name = "Kanave"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "orjson>=3.9.10",
    "requests~=2.32.3",
]

[project.entry-points."mwgg.plugins"]
"osu.WorldClass" = "osu.Register:WORLD_CLASS"
"osu.WebWorldClass" = "osu.Register:WEB_WORLD_CLASS"
"osu.Client" = "osu.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["osu*", "osu"]
exclude = ["osu/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
