[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "seaofthieves"
dynamic = ["version"]
description = "Sea of Thieves"
authors = [
    {name = "EthanTheEpic"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"seaofthieves.WorldClass" = "seaofthieves.Register:WORLD_CLASS"
"seaofthieves.WebWorldClass" = "seaofthieves.Register:WEB_WORLD_CLASS"
"seaofthieves.Client" = "seaofthieves.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "seaofthieves.Register:VERSION"}
