[project]
name = "marioland2"
version = "1.0.0"
description = "Super Mario Land 2 is a classic platformer that follows Mario on a quest to reclaim his castle from the villainous Wario. This iconic game features 32 levels, unique power-ups, and introduces Wario as Mario's arch-rival."
authors = [
    {name = " Alchav"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"marioland2.WorldClass" = "marioland2.Register:WORLD_CLASS"
"marioland2.WebWorldClass" = "marioland2.Register:WEB_WORLD_CLASS"
"marioland2.Client" = "marioland2.Register:CLIENT_FUNCTION"
