[project]
name = "sm"
version = "1.0.0"
description = "This is Very Adaptive Randomizer of Items and Areas for Super Metroid (VARIA SM). It supports a wide range of options to randomize Item locations, required skills and even the connections between the main Areas!"
authors = [
    {name = "lordlou"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sm.WorldClass" = "sm.Register:WORLD_CLASS"
"sm.WebWorldClass" = "sm.Register:WEB_WORLD_CLASS"
"sm.Client" = "sm.Register:CLIENT_FUNCTION"
