[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sm"
dynamic = ["version"]
description = "Super Metroid"
authors = [
    {name = "lordlou"}
]
license = "MIT AND (GPL-2.0-only)"
license_files = [
    "variaRandomizer/LICENSE",
    "variaRandomizer/patches/ips.pl"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sm.WorldClass" = "sm.Register:WORLD_CLASS"
"sm.WebWorldClass" = "sm.Register:WEB_WORLD_CLASS"
"sm.Client" = "sm.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["sm*", "sm"]
exclude = ["sm/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
