[project]
name = "diddy_kong_racing"
version = "1.0.0"
description = "Diddy Kong Racing is a kart racing game with a story mode, complete with bosses and hidden collectibles."
authors = [
    {name = "zakwiz"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"diddy_kong_racing.WorldClass" = "diddy_kong_racing.Register:WORLD_CLASS"
"diddy_kong_racing.WebWorldClass" = "diddy_kong_racing.Register:WEB_WORLD_CLASS"
"diddy_kong_racing.Client" = "diddy_kong_racing.Register:CLIENT_FUNCTION"
