[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pokemon_emerald"
dynamic = ["version"]
description = "MultiWorld: Pokemon Emerald"
authors = [
    {name = "Zunawe"}
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"pokemon_emerald.WorldClass" = "pokemon_emerald.Register:WORLD_CLASS"
"pokemon_emerald.WebWorldClass" = "pokemon_emerald.Register:WEB_WORLD_CLASS"
"pokemon_emerald.Client" = "pokemon_emerald.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["pokemon_emerald*", "pokemon_emerald"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "pokemon_emerald.Constants.VERSION"}
