[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sadx"
dynamic = ["version"]
description = "Sonic Adventure DX"
authors = [
    {name = "Classic"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sadx.WorldClass" = "sadx.Register:WORLD_CLASS"
"sadx.WebWorldClass" = "sadx.Register:WEB_WORLD_CLASS"
"sadx.Client" = "sadx.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "sadx.Register:VERSION"}
