[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "star_fox_64"
dynamic = ["version"]
description = "Star Fox 64"
authors = [
    {name = "Austin"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"star_fox_64.WorldClass" = "star_fox_64.Register:WORLD_CLASS"
"star_fox_64.WebWorldClass" = "star_fox_64.Register:WEB_WORLD_CLASS"
"star_fox_64.Client" = "star_fox_64.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "star_fox_64.Register:VERSION"}
