[project]
name = "star_fox_64"
version = "1.0.0"
description = "Star Fox 64 is a 3D rail shooter game in which the player controls one of the vehicles piloted by Fox McCloud, usually an Arwing."
authors = [
    {name = "Austin"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"star_fox_64.WorldClass" = "star_fox_64.Register:WORLD_CLASS"
"star_fox_64.WebWorldClass" = "star_fox_64.Register:WEB_WORLD_CLASS"
"star_fox_64.Client" = "star_fox_64.Register:CLIENT_FUNCTION"
