[project]
name = "gzdoom"
version = "1.0.0"
description = "gzDoom is an open-source enhanced port of the Doom engine, supporting Doom 1/2, Hexen, Heretic, and Strife, along with thousands of fan-made maps and mission packs and even a few commercial games like Hedon Bloodrite and Selaco. This randomizer comes with an automated WAD scanner that makes it easy to add support for new WADs."
authors = [
    {name = "ToxicFrog"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"gzdoom.WorldClass" = "gzdoom.Register:WORLD_CLASS"
"gzdoom.WebWorldClass" = "gzdoom.Register:WEB_WORLD_CLASS"
"gzdoom.Client" = "gzdoom.Register:CLIENT_FUNCTION"
