[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gzdoom"
dynamic = ["version"]
description = "gzDoom"
authors = [
    {name = "ToxicFrog"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"gzdoom.WorldClass" = "gzdoom.Register:WORLD_CLASS"
"gzdoom.WebWorldClass" = "gzdoom.Register:WEB_WORLD_CLASS"
"gzdoom.Client" = "gzdoom.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["gzdoom*", "gzdoom"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "gzdoom.Constants.VERSION"}
