[project]
name = "sm64ex"
version = "1.0.0"
description = "The first Super Mario game to feature 3D gameplay, it features freedom of movement within a large open world based on polygons, combined with traditional Mario gameplay, visual style, and characters."
authors = [
    {name = "N00byKing"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sm64ex.WorldClass" = "sm64ex.Register:WORLD_CLASS"
"sm64ex.WebWorldClass" = "sm64ex.Register:WEB_WORLD_CLASS"
"sm64ex.Client" = "sm64ex.Register:CLIENT_FUNCTION"
