[project]
name = "trackmania"
version = "1.0.0"
description = "Trackmania is a mechanically deep arcade racing game that is easy to pick up and addicting to master! Zoom through hundreds of thousands of user-made tracks as fast as you can!"
authors = [
    {name = "SerialBoxes"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"trackmania.WorldClass" = "trackmania.Register:WORLD_CLASS"
"trackmania.WebWorldClass" = "trackmania.Register:WEB_WORLD_CLASS"
"trackmania.Client" = "trackmania.Register:CLIENT_FUNCTION"