[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "trackmania"
dynamic = ["version"]
description = "Trackmania"
authors = [
    {name = "SerialBoxes"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"trackmania.WorldClass" = "trackmania.Register:WORLD_CLASS"
"trackmania.WebWorldClass" = "trackmania.Register:WEB_WORLD_CLASS"
"trackmania.Client" = "trackmania.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["trackmania*", "trackmania"]
exclude = ["trackmania/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
