[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kh2"
dynamic = ["version"]
description = "Kingdom Hearts 2"
authors = [
    {name = "JaredWeakStrike"},
    {name = "Shananas"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "Pymem>=1.10.0",
]

[project.entry-points."mwgg.plugins"]
"kh2.WorldClass" = "kh2.Register:WORLD_CLASS"
"kh2.WebWorldClass" = "kh2.Register:WEB_WORLD_CLASS"
"kh2.Client" = "kh2.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["kh2*", "kh2"]
exclude = ["*test*", "test*"]
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[tool.setuptools.dynamic]
version = {attr = "kh2.Constants.VERSION"}
