[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kh2"
dynamic = ["version"]
description = "Kingdom Hearts 2"
authors = [
    {name = "JaredWeakStrike & Shananas"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "Pymem>=1.10.0",
]

[project.entry-points."mwgg.plugins"]
"kh2.WorldClass" = "kh2.Register:WORLD_CLASS"
"kh2.WebWorldClass" = "kh2.Register:WEB_WORLD_CLASS"
"kh2.Client" = "kh2.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "kh2.Register:VERSION"}
