[project]
name = "wargroove2"
version = "1.0.0"
description = "Command an army, in the sequel to the hit turn based strategy game Wargroove!"
authors = [
    {name = "Fly Sniper"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"wargroove2.WorldClass" = "wargroove2.Register:WORLD_CLASS"
"wargroove2.WebWorldClass" = "wargroove2.Register:WEB_WORLD_CLASS"
"wargroove2.Client" = "wargroove2.Register:CLIENT_FUNCTION"
