[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ffmq"
dynamic = ["version"]
description = "MultiWorld: Final Fantasy Mystic Quest"
authors = [
    {name = "Alchav"}
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ffmq.WorldClass" = "ffmq.Register:WORLD_CLASS"
"ffmq.WebWorldClass" = "ffmq.Register:WEB_WORLD_CLASS"
"ffmq.Client" = "ffmq.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["ffmq*", "ffmq"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "ffmq.Constants.VERSION"}
