[project]
name = "tloz_ooa"
version = "1.0.0"
description = "The Legend of Zelda: Oracles of Ages is one of the rare Capcom entries to the series. Nayru, the oracle of ages, has been possessed by Veran, and she is now making a mess in Labrynna Gather the Essences of Times, exorcice Nayru and defeat Veran to save the timeline of Labrynna"
authors = [
    {name = "Dinopony"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tloz_ooa.WorldClass" = "tloz_ooa.Register:WORLD_CLASS"
"tloz_ooa.WebWorldClass" = "tloz_ooa.Register:WEB_WORLD_CLASS"
"tloz_ooa.Client" = "tloz_ooa.Register:CLIENT_FUNCTION"
