[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "metroidprime"
dynamic = ["version"]
description = "MultiWorld: Metroid Prime"
authors = [
    {name = "Electro15"}
]
license = "MIT AND (GPL-3.0-only)"
license-files = [
    "lib/dolphin_memory_engine/LICENSE",
    "lib/ppc_asm/LICENSE",
    "lib/py_randomprime/LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"metroidprime.WorldClass" = "metroidprime.Register:WORLD_CLASS"
"metroidprime.WebWorldClass" = "metroidprime.Register:WEB_WORLD_CLASS"
"metroidprime.Client" = "metroidprime.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["metroidprime*", "metroidprime"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "metroidprime.Constants.VERSION"}
