[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "smw"
dynamic = ["version"]
description = "Super Mario World is an action platforming game."
authors = [
    {name = "PoryGone"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"smw.WorldClass" = "smw.Register:WORLD_CLASS"
"smw.WebWorldClass" = "smw.Register:WEB_WORLD_CLASS"
"smw.Client" = "smw.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "smw.Register:VERSION"}
