[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "jakanddaxter"
dynamic = ["version"]
description = "Jak and Daxter: The Precursor Legacy"
authors = [
    {name = "massimilianodelliubaldini"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "Pymem>=1.13.0",
]

[project.entry-points."mwgg.plugins"]
"jakanddaxter.WorldClass" = "jakanddaxter.Register:WORLD_CLASS"
"jakanddaxter.WebWorldClass" = "jakanddaxter.Register:WEB_WORLD_CLASS"
"jakanddaxter.Client" = "jakanddaxter.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["jakanddaxter*", "jakanddaxter"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "jakanddaxter.Constants.VERSION"}
