[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tloz"
dynamic = ["version"]
description = "The Legend of Zelda"
authors = [
    {name = "Rosalie-A & t3hf1gm3nt"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "bsdiff4>=1.2.2",
]

[project.entry-points."mwgg.plugins"]
"tloz.WorldClass" = "tloz.Register:WORLD_CLASS"
"tloz.WebWorldClass" = "tloz.Register:WEB_WORLD_CLASS"
"tloz.Client" = "tloz.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["tloz*", "tloz"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "tloz.Constants.VERSION"}
