[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "lufia2ac"
dynamic = ["version"]
description = "The Ancient Cave is a roguelike dungeon crawling game built into"
authors = [
    {name = "el-u & word_fcuk"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"lufia2ac.WorldClass" = "lufia2ac.Register:WORLD_CLASS"
"lufia2ac.WebWorldClass" = "lufia2ac.Register:WEB_WORLD_CLASS"
"lufia2ac.Client" = "lufia2ac.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "lufia2ac.Register:VERSION"}
