[project]
name = "lufia2ac"
version = "1.0.0"
description = "The Ancient Cave is a roguelike dungeon crawling game built into the RGP Lufia II. Face 99 floors of ever harder to beat monsters, random items and find new companions on the way to face the Royal Jelly in the end. Can you beat it?"
authors = [
    {name = "el-u & word_fcuk"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"lufia2ac.WorldClass" = "lufia2ac.Register:WORLD_CLASS"
"lufia2ac.WebWorldClass" = "lufia2ac.Register:WEB_WORLD_CLASS"
"lufia2ac.Client" = "lufia2ac.Register:CLIENT_FUNCTION"
