[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "hk"
dynamic = ["version"]
description = "Hollow Knight"
authors = [
    {name = "BadMagic"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"hk.WorldClass" = "hk.Register:WORLD_CLASS"
"hk.WebWorldClass" = "hk.Register:WEB_WORLD_CLASS"
"hk.Client" = "hk.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "hk.Register:VERSION"}
