[project]
name = "hk"
version = "1.0.0"
description = "Beneath the fading town of Dirtmouth sleeps a vast, ancient kingdom. Many are drawn beneath the surface, searching for riches, or glory, or answers to old secrets. As the enigmatic Knight, you’ll traverse the depths, unravel its mysteries and conquer its evils."
authors = [
    {name = "BadMagic"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"hk.WorldClass" = "hk.Register:WORLD_CLASS"
"hk.WebWorldClass" = "hk.Register:WEB_WORLD_CLASS"
"hk.Client" = "hk.Register:CLIENT_FUNCTION"
