[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "hk"
dynamic = ["version"]
description = "MultiWorld: Hollow Knight"
authors = [
    {name = "BadMagic"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"hk.WorldClass" = "hk.Register:WORLD_CLASS"
"hk.WebWorldClass" = "hk.Register:WEB_WORLD_CLASS"
"hk.Client" = "hk.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["hk*", "hk"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "hk.Constants.VERSION"}
