[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "huniepop"
dynamic = ["version"]
description = "Hunie Pop"
authors = [
    {name = "dotsofdarkness"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"huniepop.WorldClass" = "huniepop.Register:WORLD_CLASS"
"huniepop.WebWorldClass" = "huniepop.Register:WEB_WORLD_CLASS"
"huniepop.Client" = "huniepop.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "huniepop.Register:VERSION"}
