[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "satisfactory"
dynamic = ["version"]
description = "Satisfactory"
authors = [
    {name = "Jarno"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"satisfactory.WorldClass" = "satisfactory.Register:WORLD_CLASS"
"satisfactory.WebWorldClass" = "satisfactory.Register:WEB_WORLD_CLASS"
"satisfactory.Client" = "satisfactory.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "satisfactory.Register:VERSION"}
