[project]
name = "satisfactory"
version = "1.0.0"
description = "Satisfactory is a first-person open-world factory building game with a dash of exploration and combat. Explore an alien planet, create multi-story factories, and enter conveyor belt heaven!"
authors = [
    {name = "Jarno"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"satisfactory.WorldClass" = "satisfactory.Register:WORLD_CLASS"
"satisfactory.WebWorldClass" = "satisfactory.Register:WEB_WORLD_CLASS"
"satisfactory.Client" = "satisfactory.Register:CLIENT_FUNCTION"
