[project]
name = "pmd_eos"
version = "1.0.0"
description = "This is for Pokemon Mystery Dungeon Explorers of Sky, a game where you inhabit a pokemon and explore through dungeons, solve quests, and help out other Pokemon in the colony"
authors = [
    {name = "CrypticMonkey33"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"pmd_eos.WorldClass" = "pmd_eos.Register:WORLD_CLASS"
"pmd_eos.WebWorldClass" = "pmd_eos.Register:WEB_WORLD_CLASS"
"pmd_eos.Client" = "pmd_eos.Register:CLIENT_FUNCTION"
