[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "outer_wilds"
dynamic = ["version"]
description = "Outer Wilds"
authors = [
    {name = "Ixrec"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"outer_wilds.WorldClass" = "outer_wilds.Register:WORLD_CLASS"
"outer_wilds.WebWorldClass" = "outer_wilds.Register:WEB_WORLD_CLASS"
"outer_wilds.Client" = "outer_wilds.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
