[project]
name = "outer_wilds"
version = "1.0.0"
description = "Outer Wilds is a 2019 adventure video game developed by Mobius Digital. The game follows the player character as they explore a planetary system stuck in a 22-minute time loop that resets after the sun goes supernova and destroys the system."
authors = [
    {name = "Ixrec"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"outer_wilds.WorldClass" = "outer_wilds.Register:WORLD_CLASS"
"outer_wilds.WebWorldClass" = "outer_wilds.Register:WEB_WORLD_CLASS"
"outer_wilds.Client" = "outer_wilds.Register:CLIENT_FUNCTION"
