[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "xenobladex"
dynamic = ["version"]
description = "Xenoblade X"
authors = [
    {name = "Maragon"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"xenobladex.WorldClass" = "xenobladex.Register:WORLD_CLASS"
"xenobladex.WebWorldClass" = "xenobladex.Register:WEB_WORLD_CLASS"
"xenobladex.Client" = "xenobladex.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "xenobladex.Register:VERSION"}
