[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "placidplasticducksim"
dynamic = ["version"]
description = "Placid Plastic Duck Simulator"
authors = [
    {name = "SW_CreeperKing"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"placidplasticducksim.WorldClass" = "placidplasticducksim.Register:WORLD_CLASS"
"placidplasticducksim.WebWorldClass" = "placidplasticducksim.Register:WEB_WORLD_CLASS"
"placidplasticducksim.Client" = "placidplasticducksim.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["placidplasticducksim*", "placidplasticducksim"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "placidplasticducksim.Constants.VERSION"}
