[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kh1"
dynamic = ["version"]
description = "Kingdom Hearts"
authors = [
    {name = "gaithern"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"kh1.WorldClass" = "kh1.Register:WORLD_CLASS"
"kh1.WebWorldClass" = "kh1.Register:WEB_WORLD_CLASS"
"kh1.Client" = "kh1.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["kh1*", "kh1"]
exclude = ["kh1/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
