[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "witness"
dynamic = ["version"]
description = "MultiWorld: The Witness"
authors = [
    {name = "NewSoupVi"},
    {name = "blastron"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"witness.WorldClass" = "witness.Register:WORLD_CLASS"
"witness.WebWorldClass" = "witness.Register:WEB_WORLD_CLASS"
"witness.Client" = "witness.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["witness*", "witness"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "witness.Constants.VERSION"}
