[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "witness"
dynamic = ["version"]
description = "The Witness"
authors = [
    {name = "NewSoupVi & blastron"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"witness.WorldClass" = "witness.Register:WORLD_CLASS"
"witness.WebWorldClass" = "witness.Register:WEB_WORLD_CLASS"
"witness.Client" = "witness.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "witness.Register:VERSION"}
