[project]
name = "witness"
version = "1.0.0"
description = "The Witness is an open-world puzzle game with dozens of locations to explore and over 500 puzzles. Play the popular puzzle randomizer by sigma144, with an added layer of progression randomization!"
authors = [
    {name = "NewSoupVi & blastron"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"witness.WorldClass" = "witness.Register:WORLD_CLASS"
"witness.WebWorldClass" = "witness.Register:WEB_WORLD_CLASS"
"witness.Client" = "witness.Register:CLIENT_FUNCTION"
