[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sc2"
dynamic = ["version"]
description = "Starcraft 2"
authors = [
    {name = "Ziktofel"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "nest-asyncio >= 1.5.5",
]

[project.entry-points."mwgg.plugins"]
"sc2.WorldClass" = "sc2.Register:WORLD_CLASS"
"sc2.WebWorldClass" = "sc2.Register:WEB_WORLD_CLASS"
"sc2.Client" = "sc2.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "sc2.Register:VERSION"}
