[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ultrakill"
dynamic = ["version"]
description = "ULTRAKILL"
authors = [
    {name = "TRPG"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ultrakill.WorldClass" = "ultrakill.Register:WORLD_CLASS"
"ultrakill.WebWorldClass" = "ultrakill.Register:WEB_WORLD_CLASS"
"ultrakill.Client" = "ultrakill.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
