[project]
name = "ultrakill"
version = "1.0.0"
description = "MANKIND IS DEAD. BLOOD IS FUEL. HELL IS FULL."
authors = [
    {name = "TRPG"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ultrakill.WorldClass" = "ultrakill.Register:WORLD_CLASS"
"ultrakill.WebWorldClass" = "ultrakill.Register:WEB_WORLD_CLASS"
"ultrakill.Client" = "ultrakill.Register:CLIENT_FUNCTION"
