[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rac2"
dynamic = ["version"]
description = "MultiWorld: Ratchet & Clank 2"
authors = [
    {name = "Evilwb"}
]
license = "MIT"
license-files = [
    "LICENSE.md"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"rac2.WorldClass" = "rac2.Register:WORLD_CLASS"
"rac2.WebWorldClass" = "rac2.Register:WEB_WORLD_CLASS"
"rac2.Client" = "rac2.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["rac2*", "rac2"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "rac2.Constants.VERSION"}
