[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sm_map_rando"
dynamic = ["version"]
description = "After planet Zebes exploded, Mother Brain put it back together again but arranged it differently this time."
authors = [
    {name = "lordlou"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
dynamic = ["version"]
]

[project.entry-points."mwgg.plugins"]
"sm_map_rando.WorldClass" = "sm_map_rando.Register:WORLD_CLASS"
"sm_map_rando.WebWorldClass" = "sm_map_rando.Register:WEB_WORLD_CLASS"
"sm_map_rando.Client" = "sm_map_rando.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["sm_map_rando*", "sm_map_rando"]
exclude = ["sm_map_rando/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
