[project]
name = "overcooked2"
version = "1.0.0"
description = "Overcooked! 2 is a frantically paced arcade cooking game where players race against the clock to complete orders for points. Bring peace to the Onion Kingdom once again by recovering lost items and abilities, earning stars to unlock levels, and defeating the unbread horde. Levels are randomized to increase gameplay variety. Play with up to 4 friends."
authors = [
    {name = "toasterparty"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"overcooked2.WorldClass" = "overcooked2.Register:WORLD_CLASS"
"overcooked2.WebWorldClass" = "overcooked2.Register:WEB_WORLD_CLASS"
"overcooked2.Client" = "overcooked2.Register:CLIENT_FUNCTION"
