[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "overcooked2"
dynamic = ["version"]
description = "Overcooked! 2"
authors = [
    {name = "toasterparty"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"overcooked2.WorldClass" = "overcooked2.Register:WORLD_CLASS"
"overcooked2.WebWorldClass" = "overcooked2.Register:WEB_WORLD_CLASS"
"overcooked2.Client" = "overcooked2.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "overcooked2.Register:VERSION"}
