[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "earthbound"
dynamic = ["version"]
description = "EarthBound"
authors = [
    {name = "Pink Switch"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"earthbound.WorldClass" = "earthbound.Register:WORLD_CLASS"
"earthbound.WebWorldClass" = "earthbound.Register:WEB_WORLD_CLASS"
"earthbound.Client" = "earthbound.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "earthbound.Register:VERSION"}
