[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "undertale"
dynamic = ["version"]
description = "Undertale"
authors = [
    {name = "jonloveslegos"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"undertale.WorldClass" = "undertale.Register:WORLD_CLASS"
"undertale.WebWorldClass" = "undertale.Register:WEB_WORLD_CLASS"
"undertale.Client" = "undertale.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["undertale*", "undertale"]
exclude = ["undertale/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
