[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mm_recomp"
dynamic = ["version"]
description = "Majora"
authors = [
    {name = "LittleCube"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mm_recomp.WorldClass" = "mm_recomp.Register:WORLD_CLASS"
"mm_recomp.WebWorldClass" = "mm_recomp.Register:WEB_WORLD_CLASS"
"mm_recomp.Client" = "mm_recomp.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "mm_recomp.Register:VERSION"}
