[project]
name = "fm"
version = "1.0.0"
description = "Yu-Gi-Oh! Forbidden Memories is a PlayStation RPG with card-battling mechanics. Assume the role of the Prince of Egypt who transcends time in order to thwart a cataclysmic evil."
authors = [
    {name = "sg4e"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"fm.WorldClass" = "fm.Register:WORLD_CLASS"
"fm.WebWorldClass" = "fm.Register:WEB_WORLD_CLASS"
"fm.Client" = "fm.Register:CLIENT_FUNCTION"
