[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "megamix"
dynamic = ["version"]
description = "MultiWorld: Hatsune Miku Project Diva Mega Mix+"
authors = [
    {name = "Cynichill"}
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"megamix.WorldClass" = "megamix.Register:WORLD_CLASS"
"megamix.WebWorldClass" = "megamix.Register:WEB_WORLD_CLASS"
"megamix.Client" = "megamix.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["megamix*", "megamix"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "megamix.Constants.VERSION"}
