[project]
name = "megamix"
version = "1.0.0"
description = "Hatsune Miku: Project Diva Mega Mix+ is a rhythm game where you hit notes to the beat of one of 250+ songs. Play through a selection of randomly chosen songs, collecting leeks until you have enough to play and complete the goal song!"
authors = [
    {name = "Cynichill"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"megamix.WorldClass" = "megamix.Register:WORLD_CLASS"
"megamix.WebWorldClass" = "megamix.Register:WEB_WORLD_CLASS"
"megamix.Client" = "megamix.Register:CLIENT_FUNCTION"
