[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dlcquest"
dynamic = ["version"]
description = "DLCQuest"
authors = [
    {name = "axe-y & Kaito Kid"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dlcquest.WorldClass" = "dlcquest.Register:WORLD_CLASS"
"dlcquest.WebWorldClass" = "dlcquest.Register:WEB_WORLD_CLASS"
"dlcquest.Client" = "dlcquest.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "dlcquest.Register:VERSION"}
