[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "wl"
dynamic = ["version"]
description = "Wario Land"
authors = [
    {name = "rand0"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"wl.WorldClass" = "wl.Register:WORLD_CLASS"
"wl.WebWorldClass" = "wl.Register:WEB_WORLD_CLASS"
"wl.Client" = "wl.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["wl*", "wl"]
exclude = ["wl/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
