[project]
name = "peaks_of_yore"
version = "1.0.0"
description = "Peaks of Yore is a first-person physics-based "climb-em-up" adventure set in 1887. Steel your nerves and perfect your climbing skills as you ascend the rock wall, traverse difficult routes, and encounter many challenges and obstacles."
authors = [
    {name = "c0der23"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"peaks_of_yore.WorldClass" = "peaks_of_yore.Register:WORLD_CLASS"
"peaks_of_yore.WebWorldClass" = "peaks_of_yore.Register:WEB_WORLD_CLASS"
"peaks_of_yore.Client" = "peaks_of_yore.Register:CLIENT_FUNCTION"
