[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dkc3"
dynamic = ["version"]
description = "Donkey Kong Country 3 is an action platforming game."
authors = [
    {name = "PoryGone"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dkc3.WorldClass" = "dkc3.Register:WORLD_CLASS"
"dkc3.WebWorldClass" = "dkc3.Register:WEB_WORLD_CLASS"
"dkc3.Client" = "dkc3.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["dkc3*", "dkc3"]
exclude = ["dkc3/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
