[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "terraria"
dynamic = ["version"]
description = "Terraria"
authors = [
    {name = "Seldom-SE"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"terraria.WorldClass" = "terraria.Register:WORLD_CLASS"
"terraria.WebWorldClass" = "terraria.Register:WEB_WORLD_CLASS"
"terraria.Client" = "terraria.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "terraria.Register:VERSION"}
