[project]
name = "sims4"
version = "1.0.0"
description = "The Sims 4 is the fourth installment in The Sims franchise. Like the previous games in the series, The Sims 4 focuses on creating and controlling a neighborhood of virtual people, called "Sims"."
authors = [
    {name = "bennydreamly"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sims4.WorldClass" = "sims4.Register:WORLD_CLASS"
"sims4.WebWorldClass" = "sims4.Register:WEB_WORLD_CLASS"
"sims4.Client" = "sims4.Register:CLIENT_FUNCTION"
