[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sims4"
dynamic = ["version"]
description = "The Sims 4"
authors = [
    {name = "bennydreamly"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sims4.WorldClass" = "sims4.Register:WORLD_CLASS"
"sims4.WebWorldClass" = "sims4.Register:WEB_WORLD_CLASS"
"sims4.Client" = "sims4.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "sims4.Register:VERSION"}
