[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "spire"
dynamic = ["version"]
description = "Slay the Spire"
authors = [
    {name = "KonoTyran"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"spire.WorldClass" = "spire.Register:WORLD_CLASS"
"spire.WebWorldClass" = "spire.Register:WEB_WORLD_CLASS"
"spire.Client" = "spire.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["spire*", "spire"]
exclude = ["spire/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
