[project]
name = "ff1"
version = "1.0.0"
description = "Final Fantasy 1, originally released on the NES on 1987, is the game that started the beloved, long running series. The randomizer takes the original 8-bit Final Fantasy game for NES (USA edition) and allows you to shuffle important aspects like the location of key items, the difficulty of monsters and fiends, and even the location of towns and dungeons. Part puzzle and part speed-run, it breathes new life into one of the most influential games ever made."
authors = [
    {name = "jtoyoda (currently unmaintained)"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ff1.WorldClass" = "ff1.Register:WORLD_CLASS"
"ff1.WebWorldClass" = "ff1.Register:WEB_WORLD_CLASS"
"ff1.Client" = "ff1.Register:CLIENT_FUNCTION"
