[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "shivers"
dynamic = ["version"]
description = "Shivers"
authors = [
    {name = "GodlFire & korydondzila"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"shivers.WorldClass" = "shivers.Register:WORLD_CLASS"
"shivers.WebWorldClass" = "shivers.Register:WEB_WORLD_CLASS"
"shivers.Client" = "shivers.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["shivers*", "shivers"]
exclude = ["shivers/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
