[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mm2"
dynamic = ["version"]
description = "MultiWorld: Mega Man 2"
authors = [
    {name = "Silvris"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mm2.WorldClass" = "mm2.Register:WORLD_CLASS"
"mm2.WebWorldClass" = "mm2.Register:WEB_WORLD_CLASS"
"mm2.Client" = "mm2.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["mm2*", "mm2"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "mm2.Constants.VERSION"}
