[project]
name = "mm2"
version = "1.0.0"
description = "In the year 200X, following his prior defeat by Mega Man, the evil Dr. Wily has returned to take over the world with his own group of Robot Masters. Mega Man once again sets out to defeat the eight Robot Masters and stop Dr. Wily."
authors = [
    {name = "Silvris"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mm2.WorldClass" = "mm2.Register:WORLD_CLASS"
"mm2.WebWorldClass" = "mm2.Register:WEB_WORLD_CLASS"
"mm2.Client" = "mm2.Register:CLIENT_FUNCTION"
