[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "yachtdice"
dynamic = ["version"]
description = "Yacht Dice is a straightforward game, custom-made for Archipelago,"
authors = [
    {name = "Spineraks"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"yachtdice.WorldClass" = "yachtdice.Register:WORLD_CLASS"
"yachtdice.WebWorldClass" = "yachtdice.Register:WEB_WORLD_CLASS"
"yachtdice.Client" = "yachtdice.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
