[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "doom_ii"
dynamic = ["version"]
description = "DOOM II"
authors = [
    {name = "Daivuk"},
    {name = "Kaito Sinclaire"}
]
license = "Zlib"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"doom_ii.WorldClass" = "doom_ii.Register:WORLD_CLASS"
"doom_ii.WebWorldClass" = "doom_ii.Register:WEB_WORLD_CLASS"
"doom_ii.Client" = "doom_ii.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["doom_ii*", "doom_ii"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "doom_ii.Constants.VERSION"}
