[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "doom_1993"
dynamic = ["version"]
description = "DOOM 1993"
authors = [
    {name = "Daivuk"},
    {name = "Kaito Sinclaire"}
]
license = "Zlib"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"doom_1993.WorldClass" = "doom_1993.Register:WORLD_CLASS"
"doom_1993.WebWorldClass" = "doom_1993.Register:WEB_WORLD_CLASS"
"doom_1993.Client" = "doom_1993.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["doom_1993*", "doom_1993"]
exclude = ["doom_1993/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
