[project]
name = "doom_1993"
version = "1.0.0"
description = "Developed by id Software, and originally released in 1993, DOOM pioneered and popularized the first-person shooter, setting a standard for all FPS games."
authors = [
    {name = "Daivuk & Kaito Sinclaire"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"doom_1993.WorldClass" = "doom_1993.Register:WORLD_CLASS"
"doom_1993.WebWorldClass" = "doom_1993.Register:WEB_WORLD_CLASS"
"doom_1993.Client" = "doom_1993.Register:CLIENT_FUNCTION"
