[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "zelda2"
dynamic = ["version"]
description = "Zelda II: The Adventure of Link"
authors = [
    {name = "Pink Switch"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"zelda2.WorldClass" = "zelda2.Register:WORLD_CLASS"
"zelda2.WebWorldClass" = "zelda2.Register:WEB_WORLD_CLASS"
"zelda2.Client" = "zelda2.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["zelda2*", "zelda2"]
exclude = ["zelda2/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
