[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "faxanadu"
dynamic = ["version"]
description = "Faxanadu"
authors = [
    {name = "Daivuk"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"faxanadu.WorldClass" = "faxanadu.Register:WORLD_CLASS"
"faxanadu.WebWorldClass" = "faxanadu.Register:WEB_WORLD_CLASS"
"faxanadu.Client" = "faxanadu.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "faxanadu.Register:VERSION"}
