[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "musedash"
dynamic = ["version"]
description = "Muse Dash"
authors = [
    {name = "DeamonHunter"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"musedash.WorldClass" = "musedash.Register:WORLD_CLASS"
"musedash.WebWorldClass" = "musedash.Register:WEB_WORLD_CLASS"
"musedash.Client" = "musedash.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["musedash*", "musedash"]
exclude = ["musedash/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
