[project]
name = "musedash"
version = "1.0.0"
description = "Muse Dash is a rhythm game where you hit objects to the beat of one of 400+ songs. Play through a selection of randomly chosen songs, collecting music sheets until you have enough to play and complete the goal song!"
authors = [
    {name = "DeamonHunter"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"musedash.WorldClass" = "musedash.Register:WORLD_CLASS"
"musedash.WebWorldClass" = "musedash.Register:WEB_WORLD_CLASS"
"musedash.Client" = "musedash.Register:CLIENT_FUNCTION"
