[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "factorio"
dynamic = ["version"]
description = "MultiWorld: Factorio"
authors = [
    {name = "Berserker66"}
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "factorio-rcon-py>=2.1.2",
]

[project.entry-points."mwgg.plugins"]
"factorio.WorldClass" = "factorio.Register:WORLD_CLASS"
"factorio.WebWorldClass" = "factorio.Register:WEB_WORLD_CLASS"
"factorio.Client" = "factorio.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["factorio*", "factorio"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "factorio.Constants.VERSION"}
