[project]
name = "inscryption"
version = "1.0.0"
description = "Inscryption is an inky black card-based odyssey that blends the deckbuilding roguelike, escape-room style puzzles, and psychological horror into a blood-laced smoothie. Darker still are the secrets inscrybed upon the cards..."
authors = [
    {name = "DrBibop"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"inscryption.WorldClass" = "inscryption.Register:WORLD_CLASS"
"inscryption.WebWorldClass" = "inscryption.Register:WEB_WORLD_CLASS"
"inscryption.Client" = "inscryption.Register:CLIENT_FUNCTION"
