[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "inscryption"
dynamic = ["version"]
description = "Inscryption"
authors = [
    {name = "DrBibop"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"inscryption.WorldClass" = "inscryption.Register:WORLD_CLASS"
"inscryption.WebWorldClass" = "inscryption.Register:WEB_WORLD_CLASS"
"inscryption.Client" = "inscryption.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["inscryption*", "inscryption"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "inscryption.Constants.VERSION"}
