[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tboir"
dynamic = ["version"]
description = "The Binding of Isaac Repentance"
authors = [
    {name = "Cyb3R"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tboir.WorldClass" = "tboir.Register:WORLD_CLASS"
"tboir.WebWorldClass" = "tboir.Register:WEB_WORLD_CLASS"
"tboir.Client" = "tboir.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
