[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "cvcotm"
dynamic = ["version"]
description = "Castlevania - Circle of the Moon"
authors = [
    {name = "LiquidCat64"}
]
license = "MIT AND (Apache-2.0)"
license_files = [
    "LICENSES.txt"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"cvcotm.WorldClass" = "cvcotm.Register:WORLD_CLASS"
"cvcotm.WebWorldClass" = "cvcotm.Register:WEB_WORLD_CLASS"
"cvcotm.Client" = "cvcotm.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "cvcotm.Register:VERSION"}
