[project]
name = "cvcotm"
version = "1.0.0"
description = "Castlevania: Circle of the Moon is a launch title for the Game Boy Advance and the first of three Castlevania games released for the handheld in the "Metroidvania" format. As Nathan Graves, wielding the Hunter Whip and utilizing the Dual Set-Up System for new possibilities, you must battle your way through Camilla's castle and rescue your master from a demonic ritual to restore the Count's power..."
authors = [
    {name = "LiquidCat64"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"cvcotm.WorldClass" = "cvcotm.Register:WORLD_CLASS"
"cvcotm.WebWorldClass" = "cvcotm.Register:WEB_WORLD_CLASS"
"cvcotm.Client" = "cvcotm.Register:CLIENT_FUNCTION"
