[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ror2"
dynamic = ["version"]
description = "Risk of Rain 2"
authors = [
    {name = "Sneaki"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ror2.WorldClass" = "ror2.Register:WORLD_CLASS"
"ror2.WebWorldClass" = "ror2.Register:WEB_WORLD_CLASS"
"ror2.Client" = "ror2.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "ror2.Register:VERSION"}
