[project]
name = "ror2"
version = "1.0.0"
description = "Escape a chaotic alien planet by fighting through hordes of frenzied monsters – with your friends, or on your own. Combine loot in surprising ways and master each character until you become the havoc you feared upon your first crash landing."
authors = [
    {name = "Sneaki"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ror2.WorldClass" = "ror2.Register:WORLD_CLASS"
"ror2.WebWorldClass" = "ror2.Register:WEB_WORLD_CLASS"
"ror2.Client" = "ror2.Register:CLIENT_FUNCTION"
