[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "hcniko"
dynamic = ["version"]
description = "MultiWorld: Here Comes Niko!"
authors = [
    {name = "nieli"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"hcniko.WorldClass" = "hcniko.Register:WORLD_CLASS"
"hcniko.WebWorldClass" = "hcniko.Register:WEB_WORLD_CLASS"
"hcniko.Client" = "hcniko.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["hcniko*", "hcniko"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "hcniko.Constants.VERSION"}
