[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "shapez"
dynamic = ["version"]
description = "shapez is an automation game about cutting, rotating, stacking, and painting shapes, that you extract from randomly"
authors = [
    {name = "Slimey"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"shapez.WorldClass" = "shapez.Register:WORLD_CLASS"
"shapez.WebWorldClass" = "shapez.Register:WEB_WORLD_CLASS"
"shapez.Client" = "shapez.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["shapez*", "shapez"]
exclude = ["shapez/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
