[project]
name = "shapez"
version = "1.0.0"
description = "shapez is an automation game about cutting, rotating, stacking, and painting shapes, that you extract from randomly generated patches on an infinite canvas, without the need to manage your infinite resources or to pay for building your factories."
authors = [
    {name = "Unknown"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"shapez.WorldClass" = "shapez.Register:WORLD_CLASS"
"shapez.WebWorldClass" = "shapez.Register:WEB_WORLD_CLASS"
"shapez.Client" = "shapez.Register:CLIENT_FUNCTION"
