[project]
name = "tp"
version = "1.0.0"
description = "Join Link and Midna on their adventure through Hyrule in Twilight Princess."
authors = [
    {name = "WritingHusky"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tp.WorldClass" = "tp.Register:WORLD_CLASS"
"tp.WebWorldClass" = "tp.Register:WEB_WORLD_CLASS"
"tp.Client" = "tp.Register:CLIENT_FUNCTION"
