[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tp"
dynamic = ["version"]
description = "The Legend of Zelda: Twilight Princess"
authors = [
    {name = "WritingHusky"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tp.WorldClass" = "tp.Register:WORLD_CLASS"
"tp.WebWorldClass" = "tp.Register:WEB_WORLD_CLASS"
"tp.Client" = "tp.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "tp.Register:VERSION"}
