[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gstla"
dynamic = ["version"]
description = "MultiWorld: Golden Sun The Lost Age"
authors = [
    {name = "Dragion"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "requests >= 2.28.2",
]

[project.entry-points."mwgg.plugins"]
"gstla.WorldClass" = "gstla.Register:WORLD_CLASS"
"gstla.WebWorldClass" = "gstla.Register:WEB_WORLD_CLASS"
"gstla.Client" = "gstla.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["gstla*", "gstla"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "gstla.Constants.VERSION"}
