[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sonic_heroes"
dynamic = ["version"]
description = "Sonic Heroes is a 2003 platform game developed by Sonic Team USA. The player races a team of series characters through levels to amass rings,"
authors = [
    {name = "xMcacutt"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sonic_heroes.WorldClass" = "sonic_heroes.Register:WORLD_CLASS"
"sonic_heroes.WebWorldClass" = "sonic_heroes.Register:WEB_WORLD_CLASS"
"sonic_heroes.Client" = "sonic_heroes.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["sonic_heroes*", "sonic_heroes"]
exclude = ["sonic_heroes/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
