[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sonic_heroes"
dynamic = ["version"]
description = "MultiWorld: Sonic Heroes"
authors = [
    {name = "xMcacutt"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sonic_heroes.WorldClass" = "sonic_heroes.Register:WORLD_CLASS"
"sonic_heroes.WebWorldClass" = "sonic_heroes.Register:WEB_WORLD_CLASS"
"sonic_heroes.Client" = "sonic_heroes.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["sonic_heroes*", "sonic_heroes"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "sonic_heroes.Constants.VERSION"}
