[project]
name = "dkc2"
version = "1.0.0"
description = "Donkey Kong Country 2 is an action platforming game. Play as Diddy Kong and his girlfriend Dixie as they go to Crocodile Isle to rescue Donkey Kong from the clutches of Kaptain K. Rool."
authors = [
    {name = "lx5"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dkc2.WorldClass" = "dkc2.Register:WORLD_CLASS"
"dkc2.WebWorldClass" = "dkc2.Register:WEB_WORLD_CLASS"
"dkc2.Client" = "dkc2.Register:CLIENT_FUNCTION"
