[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dkc2"
dynamic = ["version"]
description = "Donkey Kong Country 2"
authors = [
    {name = "lx5"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"dkc2.WorldClass" = "dkc2.Register:WORLD_CLASS"
"dkc2.WebWorldClass" = "dkc2.Register:WEB_WORLD_CLASS"
"dkc2.Client" = "dkc2.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "dkc2.Register:VERSION"}
