[project]
name = "k64"
version = "1.0.0"
description = "After Dark Matter attacks the distant Ripple Star's crystal, the young Ribbon attempts to flee with the crystal to save it. The crystal shattered, stranding Ribbon in Dream Land. Now it's up to Kirby and friends to travel the galaxy in order to restore the shattered crystal, and bring peace to the world."
authors = [
    {name = "Silvris"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"k64.WorldClass" = "k64.Register:WORLD_CLASS"
"k64.WebWorldClass" = "k64.Register:WEB_WORLD_CLASS"
"k64.Client" = "k64.Register:CLIENT_FUNCTION"
