[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "k64"
dynamic = ["version"]
description = "Kirby 64 - The Crystal Shards"
authors = [
    {name = "Silvris"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"k64.WorldClass" = "k64.Register:WORLD_CLASS"
"k64.WebWorldClass" = "k64.Register:WEB_WORLD_CLASS"
"k64.Client" = "k64.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "k64.Register:VERSION"}
