[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pseudoregalia"
dynamic = ["version"]
description = "Pseudoregalia"
authors = [
    {name = "LittleMeowMeow & qwint"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"pseudoregalia.WorldClass" = "pseudoregalia.Register:WORLD_CLASS"
"pseudoregalia.WebWorldClass" = "pseudoregalia.Register:WEB_WORLD_CLASS"
"pseudoregalia.Client" = "pseudoregalia.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
