[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pseudoregalia"
dynamic = ["version"]
description = "MultiWorld: Pseudoregalia"
authors = [
    {name = "LittleMeowMeow"},
    {name = "qwint"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"pseudoregalia.WorldClass" = "pseudoregalia.Register:WORLD_CLASS"
"pseudoregalia.WebWorldClass" = "pseudoregalia.Register:WEB_WORLD_CLASS"
"pseudoregalia.Client" = "pseudoregalia.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["pseudoregalia*", "pseudoregalia"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "pseudoregalia.Constants.VERSION"}
