[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sotn"
dynamic = ["version"]
description = "MultiWorld: Symphony of the Night"
authors = [
    {name = "Lockmau"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sotn.WorldClass" = "sotn.Register:WORLD_CLASS"
"sotn.WebWorldClass" = "sotn.Register:WEB_WORLD_CLASS"
"sotn.Client" = "sotn.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["sotn*", "sotn"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "sotn.Constants.VERSION"}
