[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tyrian"
dynamic = ["version"]
description = "Tyrian"
authors = [
    {name = "Kaito Sinclaire"}
]
license = "Zlib"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tyrian.WorldClass" = "tyrian.Register:WORLD_CLASS"
"tyrian.WebWorldClass" = "tyrian.Register:WEB_WORLD_CLASS"
"tyrian.Client" = "tyrian.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
