[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ss"
dynamic = ["version"]
description = "What if that's Zelda down there, and she's sending me a signal? It's a sign!"
authors = [
    {name = "Battlecats59"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "dolphin-memory-engine>=1.3.0",
]

[project.entry-points."mwgg.plugins"]
"ss.WorldClass" = "ss.Register:WORLD_CLASS"
"ss.WebWorldClass" = "ss.Register:WEB_WORLD_CLASS"
"ss.Client" = "ss.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "ss.Register:VERSION"}
