[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ss"
dynamic = ["version"]
description = "Skyward Sword"
authors = [
    {name = "Battlecats59"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

dependencies = [
    "dolphin-memory-engine>=1.3.0",
]

[project.entry-points."mwgg.plugins"]
"ss.WorldClass" = "ss.Register:WORLD_CLASS"
"ss.WebWorldClass" = "ss.Register:WEB_WORLD_CLASS"
"ss.Client" = "ss.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["ss*", "ss"]
exclude = ["ss/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
