[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "enderlilies"
dynamic = ["version"]
description = "Ender Lilies"
authors = [
    {name = "Trexounay"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"enderlilies.WorldClass" = "enderlilies.Register:WORLD_CLASS"
"enderlilies.WebWorldClass" = "enderlilies.Register:WEB_WORLD_CLASS"
"enderlilies.Client" = "enderlilies.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "enderlilies.Register:VERSION"}
