[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "yugioh06"
dynamic = ["version"]
description = "Yu-Gi-Oh! 2006"
authors = [
    {name = "Rensen3"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"yugioh06.WorldClass" = "yugioh06.Register:WORLD_CLASS"
"yugioh06.WebWorldClass" = "yugioh06.Register:WEB_WORLD_CLASS"
"yugioh06.Client" = "yugioh06.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["yugioh06*", "yugioh06"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "yugioh06.Constants.VERSION"}
