[project]
name = "mlss"
version = "1.0.0"
description = "File name of the MLSS US rom"
authors = [
    {name = "jamesbrq"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mlss.WorldClass" = "mlss.Register:WORLD_CLASS"
"mlss.WebWorldClass" = "mlss.Register:WEB_WORLD_CLASS"
"mlss.Client" = "mlss.Register:CLIENT_FUNCTION"
