[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "shorthike"
dynamic = ["version"]
description = "A Short Hike"
authors = [
    {name = "chandler05 & BrandenEK"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"shorthike.WorldClass" = "shorthike.Register:WORLD_CLASS"
"shorthike.WebWorldClass" = "shorthike.Register:WEB_WORLD_CLASS"
"shorthike.Client" = "shorthike.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "shorthike.Register:VERSION"}
