[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "wl4"
dynamic = ["version"]
description = "Wario Land 4"
authors = [
    {name = "lil David"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"wl4.WorldClass" = "wl4.Register:WORLD_CLASS"
"wl4.WebWorldClass" = "wl4.Register:WEB_WORLD_CLASS"
"wl4.Client" = "wl4.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
