[project]
name = "wl4"
version = "1.0.0"
description = "A golden pyramid has been discovered deep in the jungle, and Wario has set out to rob it. But when he enters, he finds the Golden Diva's curse has taken away his moves! To escape with his life and more importantly, the treasure, Wario must find his abilities to defeat the passage bosses and the Golden Diva."
authors = [
    {name = "lil David"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"wl4.WorldClass" = "wl4.Register:WORLD_CLASS"
"wl4.WebWorldClass" = "wl4.Register:WEB_WORLD_CLASS"
"wl4.Client" = "wl4.Register:CLIENT_FUNCTION"
