[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ladx"
dynamic = ["version"]
description = "Link's Awakening DX Beta"
authors = [
    {name = "threeandthree"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ladx.WorldClass" = "ladx.Register:WORLD_CLASS"
"ladx.WebWorldClass" = "ladx.Register:WEB_WORLD_CLASS"
"ladx.Client" = "ladx.Register:CLIENT_FUNCTION"
[tool.setuptools.dynamic]
version = {attr = "ladx.Register:VERSION"}
