[project]
name = "ladx"
version = "12.0"
description = "After a previous adventure, Link is stranded on Koholint Island, full of mystery and familiar faces. Gather the 8 Instruments of the Sirens to wake the Wind Fish, so that Link can go home!"
authors = [
    {name = "threeandthree"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"ladx.WorldClass" = "ladx.Register:WORLD_CLASS"
"ladx.WebWorldClass" = "ladx.Register:WEB_WORLD_CLASS"
"ladx.Client" = "ladx.Register:CLIENT_FUNCTION"