[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tunic"
dynamic = ["version"]
description = "TUNIC"
authors = [
    {name = "SilentSR & ScipioWright"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tunic.WorldClass" = "tunic.Register:WORLD_CLASS"
"tunic.WebWorldClass" = "tunic.Register:WEB_WORLD_CLASS"
"tunic.Client" = "tunic.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
