[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mmbn3"
dynamic = ["version"]
description = "MegaMan Battle Network 3"
authors = [
    {name = "digiholic"}
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"mmbn3.WorldClass" = "mmbn3.Register:WORLD_CLASS"
"mmbn3.WebWorldClass" = "mmbn3.Register:WEB_WORLD_CLASS"
"mmbn3.Client" = "mmbn3.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["mmbn3*", "mmbn3"]
exclude = ["mmbn3/test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
