[project]
name = "timespinner"
version = "1.0.0"
description = "Timespinner is a beautiful metroidvania inspired by classic 90s action-platformers. Travel back in time to change fate itself. Join timekeeper Lunais on her quest for revenge against the empire that killed her family."
authors = [
    {name = "Jarno458"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"timespinner.WorldClass" = "timespinner.Register:WORLD_CLASS"
"timespinner.WebWorldClass" = "timespinner.Register:WEB_WORLD_CLASS"
"timespinner.Client" = "timespinner.Register:CLIENT_FUNCTION"
