[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "timespinner"
dynamic = ["version"]
description = "Timespinner"
authors = [
    {name = "Jarno458"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"timespinner.WorldClass" = "timespinner.Register:WORLD_CLASS"
"timespinner.WebWorldClass" = "timespinner.Register:WEB_WORLD_CLASS"
"timespinner.Client" = "timespinner.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "timespinner.Register:VERSION"}
