[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sly1"
dynamic = ["version"]
description = "Sly Cooper and the Thievius Raccoonus"
authors = [
    {name = "Philiard"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sly1.WorldClass" = "sly1.Register:WORLD_CLASS"
"sly1.WebWorldClass" = "sly1.Register:WEB_WORLD_CLASS"
"sly1.Client" = "sly1.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
