[project]
name = "meritous"
version = "1.0.0"
description = "Meritous Gaiden is a procedurally generated bullet-hell dungeon crawl game. Five generations after the Orcus Dome incident, strange experiments conducted in a new structure on the moon are tearing at the very fabric of reality..."
authors = [
    {name = "FelicitusNeko"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"meritous.WorldClass" = "meritous.Register:WORLD_CLASS"
"meritous.WebWorldClass" = "meritous.Register:WEB_WORLD_CLASS"
"meritous.Client" = "meritous.Register:CLIENT_FUNCTION"
