[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "meritous"
dynamic = ["version"]
description = "Meritous Gaiden is a procedurally generated bullet-hell dungeon crawl game."
authors = [
    {name = "FelicitusNeko"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"meritous.WorldClass" = "meritous.Register:WORLD_CLASS"
"meritous.WebWorldClass" = "meritous.Register:WEB_WORLD_CLASS"
"meritous.Client" = "meritous.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "meritous.Register:VERSION"}
