[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "osrs"
dynamic = ["version"]
description = "Old School Runescape"
authors = [
    {name = "digiholic"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"osrs.WorldClass" = "osrs.Register:WORLD_CLASS"
"osrs.WebWorldClass" = "osrs.Register:WEB_WORLD_CLASS"
"osrs.Client" = "osrs.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
