[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sa2b"
dynamic = ["version"]
description = "Sonic Adventure 2 Battle is an action platforming game. Play as Sonic, Tails, Knuckles, Shadow, Rouge, and Eggman across 31 stages and prevent the destruction of the earth."
authors = [
    {name = "PoryGone & RaspberrySpace"}
]
license = "MIT"
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"sa2b.WorldClass" = "sa2b.Register:WORLD_CLASS"
"sa2b.WebWorldClass" = "sa2b.Register:WEB_WORLD_CLASS"
"sa2b.Client" = "sa2b.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "sa2b.Register:VERSION"}
