[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "papermario"
dynamic = ["version"]
description = "MultiWorld: Paper Mario"
authors = [
    {name = "JKB"}
]
license = "MIT"
license-files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"papermario.WorldClass" = "papermario.Register:WORLD_CLASS"
"papermario.WebWorldClass" = "papermario.Register:WEB_WORLD_CLASS"
"papermario.Client" = "papermario.Register:CLIENT_FUNCTION"

[tool.setuptools.packages.find]
where = ["."]
include = ["papermario*", "papermario"]
exclude = ["*test*", "test*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "papermario.Constants.VERSION"}
