[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "papermario"
dynamic = ["version"]
description = "Paper Mario"
authors = [
    {name = "JKB"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"papermario.WorldClass" = "papermario.Register:WORLD_CLASS"
"papermario.WebWorldClass" = "papermario.Register:WEB_WORLD_CLASS"
"papermario.Client" = "papermario.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "Constants.VERSION"}
