[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tetrisattack"
dynamic = ["version"]
description = "Tetris Attack"
authors = [
    {name = "AgStarRay"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tetrisattack.WorldClass" = "tetrisattack.Register:WORLD_CLASS"
"tetrisattack.WebWorldClass" = "tetrisattack.Register:WEB_WORLD_CLASS"
"tetrisattack.Client" = "tetrisattack.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "tetrisattack.Register:VERSION"}
