[project]
name = "tetrisattack"
version = "1.0.0"
description = "Tetris Attack is a frantic rising blocks puzzle game. Match 3 or more same-colored panels in a row horizontally or vertically to clear them. Match 4 or more simultaneously for a Combo. Match more panels after the previous ones clear out for a Chain. In Stage Clear, each round has a set of successive stages. In Puzzle, all panels in each board must be fully cleared out using limited moves. In Vs, perform Chains and Combos to attack."
authors = [
    {name = "AgStarRay"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"tetrisattack.WorldClass" = "tetrisattack.Register:WORLD_CLASS"
"tetrisattack.WebWorldClass" = "tetrisattack.Register:WEB_WORLD_CLASS"
"tetrisattack.Client" = "tetrisattack.Register:CLIENT_FUNCTION"
