[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "oot"
dynamic = ["version"]
description = "The Legend of Zelda: Ocarina of Time is a 3D action/adventure game. Travel through Hyrule in two time periods,"
authors = [
    {name = "espeon65536 (currenty unmaintained)"}
]
license = "MIT"
license_files = [
    "LICENSE"
]
classifiers = [
    "Private :: Do Not Upload"
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"oot.WorldClass" = "oot.Register:WORLD_CLASS"
"oot.WebWorldClass" = "oot.Register:WEB_WORLD_CLASS"
"oot.Client" = "oot.Register:CLIENT_FUNCTION"

[tool.setuptools.dynamic]
version = {attr = "oot.Register:VERSION"}
