[project]
name = "oot"
version = "1.0.0"
description = "The Legend of Zelda: Ocarina of Time is a 3D action/adventure game. Travel through Hyrule in two time periods, learn magical ocarina songs, and explore twelve dungeons on your quest. Use Link's many items and abilities to rescue the Seven Sages, and then confront Ganondorf to save Hyrule!"
authors = [
    {name = "espeon65536 (currenty unmaintained)"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"oot.WorldClass" = "oot.Register:WORLD_CLASS"
"oot.WebWorldClass" = "oot.Register:WEB_WORLD_CLASS"
"oot.Client" = "oot.Register:CLIENT_FUNCTION"
